[quote.epigraph, , Acts 2:17]
____
And it shall come to pass in the last days, saith God,
I will pour out of my Spirit upon all flesh:
and your sons and your daughters shall prophesy.
____

[quote.epigraph, , Dan.12:4]
____
Many shall run to and fro, and knowledge shall be increased.
____

== Preface.

The author of the following short journal, was daughter of John and Deborah Wynn,
of Bradford, in Yorkshire.
Her father, when a soldier under Oliver Cromwell,
being convinced of the ushering in of a dispensation which
abolished the use of carnal weapons for the destruction of men,
laid down his arms and was discharged.

He was soon after called into another warfare, and in those times of hot persecution,
fought with undaunted courage and holy zeal under the banner of the Lamb.
He became an able minister of the everlasting Gospel of peace and purity,
and travelled much, with good success, for the promotion thereof.

For this: daughter, the only child left of seven, his care was great,
to watch over and restrain her from evil, and to inform her,
so far as her infant years were susceptible,
in things relating to religion and a future state;
wisely guarding against suffering the affectionate part to
indulge her in any thing of a tendency to her own hurt,
or which would bring a reproach on the testimony given him to bear to others.

These early endeavours, through the divine blessing,
made deep and lasting impressions on her mind;
and although when very young she was deprived of the help of so worthy a parent,
he being removed by death when she was not quite eleven years old;
yet she kept near to and in an humble dependence on Him who is a father,
and more than a father to the fatherless, whereby she gradually witnessed,
under his renewed and continued visitations, a growth in the work of regeneration;
and earnestly desiring,
that in all things she might be perfectly resigned to answer the Divine requirings;
after many deep baptisms and refinings,
about the nineteenth year of her age a dispensation of the Gospel was committed to her;
for the publishing whereof she became eminently qualified,
and in a short time gave proofs of a truly evangelical minister.
Her appearance in the work was with awfulness;
her testimony to the unrighteous was as fire amongst stubble; but to the humble,
afflicted travellers towards Sion,
it ran in a free stream of encouragement and Divine consolation.

She was sometimes led, clearly and with great authority,
to speak of a day of trial which would come upon this nation,
wherein their sandy foundation would be shaken, and their polluted rest broken,
and a decision made between the nominal professors of religion
and those who were in the life and practice thereof.

Her conversation in the world corresponded with this high calling;
in her family she kept a tender and watchful eye over those under her notice.
She was quick in discerning and prudent in admonishing;
some reaped the advantage thereof, who still retain it in remembrance.

For further information concerning this worthy deceased Friend,
the reader is referred to her husband`'s testimony, and to the journal itself;
the serious perusal whereof,
is especially recommended to those who are young in the ministry.

[.signed-section-signature]
Robert Bell
