[#john-bell-testimony, short="John Bell's Testimony"]
== John Bell`'s Testimony concerning his wife, Deborah Bell.

Deborah Bell, wife of John Bell of Bromley in Middlesex, late of Grace-church street,
London, daughter of John and Deborah Wynn, was born at Bradford in Yorkshire;
and being carefully educated in the way of truth by her pious and faithful parents,
she sought the way of the Lord, and the knowledge of his blessed truth, when very young,
and was mercifully favoured to partake of that virtue
and Divine goodness which maketh fruitful towards God,
as she frequently expressed herself.
In her minority she often earnestly desired the Lord would be
pleased to enable her to come up in doing his will,
and that in all things she might be perfectly resigned to answer his holy requirings,
and be fully given up in heart in all sincerity,
and by his grace devoted to serve and obey him, according to the ability received.
He in mercy and loving-kindness heard her humble petitions,
and granted the early visitations of his love and goodness,
in the pourings forth of his holy Spirit, and gradually,
by the work of his own Divine power, so prepared and sanctified her heart,
that she was made a vessel of honour.
For as she became acquainted with his Divine and living word, when very young,
she grew in experience of that work which is wrought by the power of Christ,
by which alone salvation and perfect redemption is witnessed;
and being an humble follower of Jesus Christ our Lord,
and through the operation of his grace,
cheerfully given up to follow these manifestations of
the Divine light and workings of the Spirit,
which are inwardly revealed, she was so fitted for her Master`'s use and service,
as early to become a branch in Christ Jesus, the true and living Vine,
bringing forth fruit to the praise and glory of God the good Husbandman.
Being led through deep travail, and close exercise and affliction of mind,
she thereby gained great experience,
and was made sensible of various states and conditions,
which tended to qualify her for that great and
weighty work whereunto she was afterwards called.

About the nineteenth year of her age,
the Lord saw meet in his wisdom to commit a
dispensation of the everlasting Gospel to her to preach;
in which service being faithful, she grew in the knowledge of God,
and had great experience of his dealings, and like the wise scribe,
who was well instructed to the kingdom,
"`Brought forth out of the good treasury of her heart,
things both new and old,`" so that she became an able minister thereof,
to the comfort and edification of the churches where she came.
Many who were unacquainted with the work of the blessed Truth in themselves,
were reached by her powerful and lively ministry; in the service of which,
she often appeared strong when in bodily weakness, which frequently attended her,
to the admiration of those who had the knowledge of her outward infirmities.

She laboured faithfully in word and doctrine,
and visited many of the meetings of Friends in most parts of England, Wales, Scotland,
and was twice in Ireland, and had good service where she came,
for she duly regarded the guidance of Truth in all her services;
and in an especial manner, when under a concern to travel on that account,
she earnestly desired to be fully satisfied of being rightly called,
and to see her way clearly opened, both as to the time when, the places where,
and the people to whom, it was her duty to minister,
and was ever very careful to return when she found her mind clear and easy.
She would often say, which I mention for the instruction of others,
That there was great danger in exceeding the commission,
by staying abroad beyond the right time.
She greatly desired that all the ministers of Christ,
who found themselves concerned to travel in the service of the Gospel,
might take due care not to miss their way on that hand, neither when in their travels,
be drawn aside out of the right line opened to them by the Truth,
through the persuasion of unwary inconsiderate people,
but wait for the power of Christ our Lord,
to preserve them steady in mind in all their
services for the promotion of the blessed Truth;
frequently repeating, That she had observed divers,
whom she believed to have been rightly drawn forth,
who yet through weakness and instability had missed their way in those particulars,
and thereby received hurt and lessened their service.

When she was under a concern to go abroad to visit the churches,
the weight of that exercise brought her very low, both in body and mind;
for she waited diligently for the counsel of God, and full satisfaction in herself,
before she made her concern known to any;
for her whole dependence was in great humility on Christ our Lord, to put her forth,
and go before her, and to give her strength and wisdom,
to discharge herself faithfully to her own comfort and peace,
the edification of the people, and his honour.
But though she was strong in the Lord, and zealously concerned for the cause of Truth,
yet by nature, she was of a weakly constitution,
and through hard travail and close exercise,
which often was upon her for the Truth`'s sake,
her bodily infirmities increased before old age came on.

Towards the latter part of her time, being often infirm,
she frequently rejoiced in the Lord, and expressed the great comfort,
peace and satisfaction, which she had in having devoted her youthful days to his service,
and being freely given up faithfully to obey his holy requirings,
whilst a degree of health and strength were granted,
and she was able to undergo such service; often saying,
"`An early devotion was very acceptable to God,
and the strength of youth could never be so well and profitably employed,
as in faithfully serving the Lord in humility and sincere obedience,
in whatsoever work he in his wisdom may be pleased to qualify them for,
and call them into; for where it happened,
that any such lived to be attended with the infirmities of old age,
the comfort and peace they would enjoy,
would be abundantly more to them than all the comforts
of this life;`" and she could by living experience say,
"`That nothing in this world was worthy to be compared with it.`"

She often earnestly desired that the sense thereof might lay hold of our youth;
that they might give up their minds to seek the Lord early,
and devote the strength of their time to his service,
that in the end they might be made partakers of the same comfort and peace,
which was her greatest joy and real cause of rejoicing,
and became more and more so as she drew near her conclusion.
And this I publish for their perusal, that if by any means they might be prevailed on,
and stirred up to consider,
how necessary and truly profitable it is to begin early
in that great duty recommended by the wise man;
"`Remember now thy Creator in the days of thy youth, while the evil days come not,
nor the years draw nigh, when thou shalt say, I have no pleasure in them.`"

Being under a concern to visit a few meetings in Hertfordshire, and as far as Huntington,
though in a weak state of health, she undertook that journey, which proved her last,
towards the middle of the seventh month, 1738.
She was from home ten days, and had six meetings, and although weak in body,
yet she appeared strong in her ministry, and had good service,
much to the satisfaction and comfort of Friends where she came; and when she came home,
she rejoiced much and said she was humbly thankful to the Lord,
who had enabled her to perform that journey,
and had given her strength to discharge herself faithfully of the concern she was under;
and that her heart was filled with that peace and comfort,
with which he is pleased to favour his obedient servants;
and that she apprehended her day`'s work was nearly finished,
for she saw no more work her great Master had for her to do;
and she had no desire to live, but to serve and glorify him.

The last time she was at the evening meeting at Bromley, about two weeks before she died,
she bore a living testimony to the Truth,
and was engaged in supplication to the Lord in a particular manner,
praying in great fervency for the preservation,
growth and settlement of the youth amongst us, in the living eternal Truth,
to the affecting and tendering of many hearts.
When she came home from the meeting, she was filled with Divine comfort, and said,
"`It is now finished,
I do not expect you will have me with you at that meeting any more.`"
Her weakness of body increased, and she taking cold, it seized her lungs,
and occasioned a hoarseness, to which she was often liable.
On the 22nd day of the eighth month, being the first-day of the week,
we went to London to meeting, but being much indisposed,
she was under some difficulty to stay the time of it, and did not go in the afternoon,
but waited for me at a Friend`'s house until meeting ended; and coming home,
she continued weakly, though a little better at times till fourth-day evening,
but grew much worse again that night and had the advice of a physician,
but it had not the desired effect.

On sixth-day morning a pleurisy came on, which much affected her breathing;
and though means were used to remove it, she found no relief; the pain grew more violent,
so that her affliction was great,
and in an humble submission she earnestly desired the Lord,
that he would give her strength to bear her pain and affliction patiently.
Her petition was fully granted, for she was endued with patience to an uncommon degree,
and bore her affliction with a firm resignation and thankfulness of heart,
and with tender love and condescension to all about her;
and abundance of sweetness she still enjoyed,
as appeared by many precious and lively expressions, which deeply affected,
and often tendered the hearts of all about her.
When her pain was very great, she expressed herself at times after the following manner;
"`This is hard work indeed;
one had need to have nothing else to do at such a time as this.
I am sure it is as much as I am able to endure to bear the afflictions of the body;
one had need not to have terror of mind besides.`"
And appealing to a young woman standing by her whom she dearly loved,
and who had duly attended her in her illness, she said,
"`Thou knowest I have had very little respite from pain since I was first taken ill;
I would have none put off the great work of repentance till such a time as this;
if I had that work to do, what a dreadful thing it would be.`"
At another time, divers young people being present, she said,
"`I would have our young people be willing to bear the cross in their youth,
and despise the shame, for that is the way to have true peace in themselves.`"
And another time she said, "`I now feel that which my soul has longed for.`"

Seeing divers young women standing round her bed,
for whose growth and settlement in the blessed Truth she had often been concerned,
she looked solidly upon them and spake on this wise; "`I was early convinced,
that unless I was born again, I could not see the kingdom of God.
I have witnessed it, and you know I have preached this doctrine to you,
and you must know it for yourselves.`"
This she spake with such authority as pierced the hearts of all present,
and I believe will not easily be forgotten.
At another time, looking steadily upon us, with a composed countenance said,
"`I have always been sincere, and never had any thing in view but the great cause of God,
and that I might be clear of the blood of all men,
and I have discharged myself faithfully; for whatsoever my hand found to do,
I did it with all my might, and never spared myself; and I am fully clear and easy,
and my day`'s work seems to be done.`"
At another time, observing the distress I was in, she looked earnestly upon me, and said,
"`The Lord brought us together, and has been with us,
and thou must give me freely up to him again, and he will support thee,
and take care of thee.`"

At another time, being in great distress of mind,
under the consideration of my great loss of so dear a companion,
if she should be removed, I asked her,
If she had not rather live with me a little longer,
if Providence saw meet? She looked pleasantly upon me, and after a little pause, said,
"`I have no desire or will of my own, I stand in the will of God.`"
At another time, under the sense of her great pain, she said,
"`I earnestly desire the Lord may release me whilst I
have strength and patience to bear my afflictions,
but I neither murmur nor repine.`"
And observing the sadness of my countenance, she said,
"`Why should I not go now? I can never go better.`"
I told her, If Providence pleased to raise her again, she might be with me longer,
and be of service, and yet go well; she readily answered, "`There may be danger in that,
I am now ready.`"

At another time, I told her, when bemoaning myself,
if the Lord should see meet to remove her from me at that time,
I believed he would receive her into the mansions of glory; she replied,
"`I never doubt that; I trust through Christ to be removed into eternal bliss,
for I am in peace, and perfectly easy.`"
At another time she looked upon me and said, "`The Lord gave me to thee,
and thou must give me up to him again.`"
And towards the latter part of her illness, being in great pain,
and observing the concern I was in for her, she said, "`My dear,
I am afraid thou holdest me.`"
I answered "`No, I have freely given thee up,
and stand resigned in the will of God;`" she looked pleasantly upon me, and replied,
"`That is very good in thee.`"
Afterwards her affliction and pain being very great and heavy upon her,
she prayed fervently, and said, "`Lord,
be pleased to grant me a little ease before I go hence and be seen of men no more.`"
And the Lord was pleased to answer her fervent supplication;
for the day before her departure, all pain and affliction seemed to be removed,
and she continued quiet and easy, in a still sweet frame of mind;
and although she spoke not much during that time, which could be perfectly heard,
yet she remained very sensible,
and her sweet and lively breathings plainly declared she
continued in inward prayer and praises unto the Lord,
her lips often moving, and sometimes expressions were heard,
tending to signify the full assurance she had of an
inheritance in eternal felicity and glory amongst the just.
Many more precious and weighty expressions she dropped during her illness,
which the distress of my mind prevented me from remembering perfectly.

About the fifth hour in the evening, being the fifth-day of the week,
and the 2nd of the ninth month, 1738, she sweetly finished her course,
and went away like an innocent lamb.
And notwithstanding the great affliction and pain she
underwent for seven days and seven nights,
that brightness and innocency, which Truth had impressed,
remained on her countenance when the soul was released and had
taken its flight into the regions of bliss and glory.

She was aged about forty-nine years, and a minister upwards of thirty years;
she was endued with many eminent gifts and qualifications, an able minister,
rightly dividing the word of Truth through that wisdom received from God,
which proved effectual to the convincing of divers,
and the edifying and reaching of many; she was zealous for the cause of God,
and of a discerning spirit and good understanding,
so that the enemies of Truth could not stand before her, for her bow abode in strength,
and her arrows were often carried to the mark, and were sharp against undue liberty,
deceit, and the works and workers of unrighteousness.

She dearly loved the children of the light,
and sincerely sympathized with such in their
afflictions who were seeking the way to Zion,
and often had a word of comfort to them.
Her heart and house were always open, according to the example of her pious parents,
to receive the ambassadors of Christ, remembering what he said;
"`And whosoever shall give to drink unto one of these little ones,
a cup of cold water only in the name of a disciple, verily I say unto you,
he shall in no wise lose his reward.`"
And likewise what he told his disciples; "`Verily, verily, I say unto you,
he that receiveth whomsoever I send, receiveth me: and he that receiveth me,
receiveth him that sent me.`"
And her delight was in the company of those who laboured for the promotion of the Gospel,
and through a good degree of experience,
she had sometimes a word of advice and encouragement to such.

She was a loving and affectionate wife, and the gift of God to me,
and as such I always prized her, a help-meet indeed both in prosperity and adversity,
a steady and cheerful companion in all the afflictions and trials which attended us,
and a true and faithful yoke-fellow in all our services in the church;
for being ever one in spirit, we became one in faith and practice,
in discerning and judgment, and our concern and labour was the same;
which nearly united us, and a life of comfort and satisfaction we lived,
our souls in the nearest union delighting in each other;
and the love and presence of God,
wherewith we were often favoured in our private retirements, sweetened every bitter cup,
and made our passage easy and pleasant to us.
But alas!
What shall I say, the Lord, who is allwise, and only knows what is best for us,
hath called her hence, who is worthy to do whatsoever he sees meet;
therefore in humble submission to his will who gave, and hath taken away,
as knowing though it is my loss, it is her everlasting gain, I rest,
and can in sincerity and Truth bless his name, who is worthy forever.

[.signed-section-signature]
John Bell

On the seventh day of the month aforesaid,
her body was accompanied from our dwelling house at Bromley,
to the meeting house in Grace-church street, London; whence, after a solemn meeting,
many being affected with the removal of so near a friend,
it was carried to Friends`' burying ground near Bunhill-fields, and buried by her mother,
according to her desire.

"`Precious in the sight of the Lord is the death of his saints.`"
