== A Short Journal of Deborah Bell

In the year 1707,
Susannah Saunders came from London into our country on a visit to Friends,
and having no companion,
with the consent of my mother and some ancient Friends of our meeting,
I accompanied her to several meetings in our parts.

The 14th day of the eighth month, we had a meeting at Highflats,
where my companion had hard labour in a plain and close testimony.
After the meeting, an ancient man who had been of some note among Friends,
but falling into reproach, and not taking the advice of the church,
had lost his condition and become troublesome, reflected upon the Friend, and told her,
she had not a right sense of the state of their meeting, for they were a faithful people;
and bid her go into the world and gather a people, and then come and preach to them;
and more to that purpose.
I was young, and had not appeared in the work of the ministry at that time,
therefore sat quietly and heard what passed, though under a great concern,
lest what he said should hurt the Friend, and discourage her in her service.

Afterwards he directed his discourse to me, saying, I was of a wrong spirit,
or I would not have come along with that woman, for they were a faithful people,
and had stood for their testimony in the persecuting times,
when others had shrunk and been unfaithful.
I told him, I was glad to hear they stood faithful in that persecuting time,
and desired they might retain their integrity,
and be enabled to stand if such another time should come;
that I had not seen much of that persecution,
but hoped he had nothing to accuse my parents of in that respect.
The value he had for them formerly not being entirely erased, he made me no reply;
and the Lord gave me strength to bear testimony against the spirit he was in;
and divers worthy ancient Friends present,
fully expressed how glad they were of our visit,
having true unity with the Friend`'s testimony,
and earnestly desired we might not be discouraged, or regard what that man said,
for he was of a contentious spirit, and had given them much trouble and exercise.
Truth came over him, and we parted with Friends in peace,
and proceeded on our journey with comfort.

We had satisfactory meetings at Burton, Pontefract, Selby, Cottness, Rawcliff,
and Fishlock, where we visited Sarah Westerdale, an honest Friend and good minister,
who lay very weak.
We had a good and comfortable time with her,
our great Lord being near to her in her affliction.
Thence we proceeded to Thorne, Blyth, Mansfield, and so to John Gratton`'s,
where we had meetings, and also an opportunity of seeing that worthy Friend.
We stayed one night at his house, and may say, he was a father indeed.

The next day we came to Nottingham, where there was a burial, to which many people came,
and our great Master owned us, made way for the testimony of Truth,
and favoured us with a good and comfortable time.
Next morning we parted in true unity and nearness;
for the Lord is gathering a people near to himself,
and makes them dear one unto another in that which changeth not; for which,
and all his mercies, let him have the praise.
My companion proceeded on her journey towards London, and I returned home,
where I safely arrived the 30th of the eighth month, in true peace,
and found my dear mother well, for which I was truly thankful unto the Lord,
and glad that I was accounted worthy to be serviceable to any of his servants.

In the year 1708, Elizabeth Richardson, an ancient and worthy woman,
was at York Quarterly Meeting, and having a concern to go into Cumberland,
our friend William Ellis, and divers other ancient Friends,
being unwilling she should travel alone,
proposed to my mother that I should accompany her, who freely consented;
and I being inclined from my childhood, to be serviceable in any thing in my power,
to the true messengers and ministers of Christ, I gave up to go.

The 19th of the fourth month I set forward, and got to William Ellis`'s,
where I lodged that night, and next day went to Settle, where I met with my companion,
and there we had a meeting; we had one also at Kendall; and passing through Shap,
came to Thomas Priestman`'s, and next morning to the Quarterly meeting for Cumberland,
where was a large women`'s meeting.
Their affairs were managed in wisdom and great unanimity, and a good meeting it was.
Next day was held a select meeting for ministers and elders,
where I had the privilege of being present, and it was a glorious meeting;
divers living testimonies were borne by some young ministers,
and suitable advice given by ancient Friends of great experience,
who had been for many years instruments of great good to the churches;
after which there was a general meeting, which was very large, and a comfortable time,
for truth came into dominion, in a great degree.

After the meeting, my dear motherly companion and I,
went to her brother Thomas Drewry`'s. Next day I visited
that worthy minister Robert Atkinson and his family;
we then proceeded to Jonathan Bell`'s near Cockermouth,
where we met with our friends Daniel Bell,
and John Bell who afterwards became my husband.
He had concluded, at the request of my companion`'s husband, in his return towards London,
to take care of her home, having conducted her in his way downwards to Leeds,
and there left her; and Daniel likewise inclining for that city,
they joined with us in company.
They were both entire strangers to me, and I to them.
Next day, being first-day, we were all at Pardsay, where we had a large and good meeting,
and another at Cockermouth that afternoon, which was very large,
our worthy friend James Dickinson, and many others from Pardsay meeting,
accompanying us thither; for my companion was much esteemed by Friends there-away.

The next meetings we took were at Windermore and Kendall.
We went also to Robert Chambers`'s, to visit a Friend who was weakly,
where we had a sweet and comfortable time together.
Next day we were at Preston meeting, where a weighty exercise fell upon me,
and a few words livingly opened upon my mind,
and a necessity was laid upon me for the first time, to deliver them to the people;
and I can truly say, I stood up in much dread and fear, and spoke what I had to say,
trembling, but afterwards felt the peace of God, by which I was comforted.

Next day we went to Lancaster Quarterly Meeting, which was very large,
and in that great assembly a weighty concern came upon me,
and according to the ability received, I discharged myself,
and sat down in the enjoyment of peace.
It was an extraordinarily good meeting; and here I met with many worthy ancient Friends,
with whom I had been acquainted from my childhood,
by their frequently being at my mother`'s house, in their travels on Truth`'s service,
and their fatherly notice was a great comfort and strength to me in that exercising time;
and for this I was humbly thankful to the Lord,
knowing him to be the fountain from whence all good comes, and I bless his name.

We had meetings at Settle and Airton,
and finding we could not reach Bradford after the last meeting, without inconvenience,
we concluded to take up at an inn, and rode into the yard.
The landlord came to the door and looked very shy upon us,
seeing we were of the people called Quakers, and did not offer to come near us;
however we alighted, went in, and were conducted into a room.
We sat down, and after some time, called for the landlord,
and waited a considerable time before he came.
We then ordered supper to be got ready, and when it was brought up,
he came into the room, and there being a little pause in silence,
he stood by the table and took off his hat, whether with an intention to say something,
as their manner is, or not, we knew not; for a Friend in the company,
being under a concern, spake a few words in prayer.
At first he seemed surprised, but was afterwards much affected,
for the power of Truth came over him, insomuch that his countenance changed,
and his carriage towards us was afterwards quite altered.
We lodged there that night, and next morning, upon our departure,
he showed great respect, telling us, If we, or any of our friends,
came that way at any time,
we might depend on the best accommodation he was capable to entertain us with;
so we parted with him in a good disposition of mind,
and that morning I got safe home to my dear mother, and found her well,
the other Friends being along with me.
I was full of peace,
and in an humble sense of the Lord`'s Divine goodness and preserving power,
and that his good presence had attended me in that journey,
my heart was filled with thanksgiving and praises to him,
and made to acknowledge he is everlastingly worthy.

We all went to our meeting, had a comfortable time,
and next morning I parted with my motherly companion, and the other Friends,
in much love and nearness; for we were truly united in the love of Christ our Lord.
They proceeded towards London, and I was left at home,
where I continued for a considerable time, in great humility and awfulness of mind,
in consideration of the weight of that work whereunto I was called,
diligently attending our own meeting;
and by waiting upon the Lord for counsel and strength, and often retiring unto Him,
upon whom my constant dependency was, I grew in experience,
and had strength and wisdom given me to discharge myself faithfully,
according to the gift freely bestowed upon me,
which gained me a place in the hearts of Friends, who were very helpful to me.

In this year, our ancient and worthy Friend Eleanor Haydock, being weakly,
sent a message to me, earnestly desiring I would pay her a visit, saying,
If she were able to travel, she would go much further to see me.
I consulted my mother about it, whose advice I greatly regarded in all my undertakings,
being a faithful woman, and of great experience in the work of Truth,
and a tender nursing mother to me, in a spiritual sense, under all my deepest exercises.
She advised me to answer the Friend`'s request; and I undertook that journey,
and in my way dropt into an evening meeting, sometimes kept at a Friend`'s house,
who had a son that had taken undue liberties and left Friends,
but was present in that meeting, and the power of Truth came over us in a great degree.
The young man was reached and much tendered, and came to me after the meeting, trembling,
and dropt many tears.
I spoke to him what was then given me, with which he was much affected,
though but a few words.
I afterwards became farther acquainted with him, for he heartily joined with Friends,
and a great reformation was wrought in him,
by that Divine power which purifies the heart,
and in process of time he had a few words in meetings.
He did not live many years, but I hope made a good end.

Next day, coming to Eleanor Haydock`'s, I was kindly received;
she rejoiced much that I had answered her request.
I stayed with her some time, and had divers good and comfortable meetings there-away,
and was also much edified and helped by that good woman`'s conversation,
being a person of great experience, well deserving the name of a mother in Israel.
After my stay with her, I returned home again in peace,
and spent much time in private retirement, in which I found strength and great comfort,
and the Lord was near in all my deep exercises, which were often weighty upon me.

In the winter of this year, we had meetings on first-day evenings, and I being young,
and much known in the town, the report of my appearing in the ministry,
excited the curiosity of many people of divers persuasions,
who flocked into these evening meetings,
where they could come without being so much observed as in the day time.
This added much to the weight of my present exercise,
and I lived a life of humility and great fear,
often fervently desiring the Lord would give me wisdom, and guide me by his own spirit,
that neither in conduct nor ministry,
I might ever do or say any thing that might discourage,
or turn any inquiring soul out of the way; and forever blessed be his name,
his ear was open to my secret prayers,
for in those crowded evening meetings we were favoured with his presence,
and had many comfortable times; for the Truth prevailed, and often came over all,
to the praise and glory of God, the Master of our assemblies.

Finding drawings in my mind to attend the Yearly Meeting to be
held at Lancaster for the northern counties,
the 29th of the First month, 1709, I set forward in company with Mary Richardson.
We took meetings in our way at Skipton, Airton, Settle, Bentham, and Yelland;
and on second-day we were at Lancaster Monthly Meeting; on third-day,
at the meeting of ministers and elders,
and on fourth-day at the general meeting for worship, which was very large;
on fifth-day at the Quarterly Meeting for the county,
and after the meeting left that town in peace,
having had a glorious and comfortable time amongst many of our brethren and sisters,
the Lord`'s power and good presence being witnessed amongst us in a large degree;
for which favour we are deeply engaged to be
humbly thankful to the God of all our mercies,
to whom the praise is due forever.

We then visited the meetings at Preston, Kendall, Grayrig, Brigflats, Dentshead,
Grisedale, Ravensend, Garsdale, and Countersel, and thence to John Routh`'s;
where I parted with my companion.
Next day I reached Bowbrighall and Bainbrig,
and having spent one day in visiting several Friends in their families,
passed on to Esker, Burton, and Scarhouse, where I had meetings; and then to Airton,
to our worthy friend William Ellis`'s, where I stayed that night;
and next day being the 23d of the second month, I got safe home,
through the preserving power of the Lord, in perfect peace,
having had a very comfortable journey;
for which my soul is humbly thankful unto the Lord,
who is near unto his bowed children and faithful servants,
and gives the reward of peace into the bosoms of
those who cast their care upon him alone,
and faithfully answer his call, and follow him fully in all things.

The summer following,
a concern came upon me to visit the meetings of Friends
in some parts of the north of England and Scotland,
and when I had fully weighed the thing, and saw my way clear,
I acquainted my mother and some other ancient Friends with it,
and they being willing to give me up, I wrote to Mary Richardson,
an elderly woman Friend, who had been my companion in another journey, querying of her,
if she had any concern or drawings that way? I received for answer,
that she was under the like concern to visit the places proposed,
and would be glad to join me in that service.
So I made preparation for my journey,
and towards the latter end of the fifth month had a certificate from our Monthly meeting;
and a great concern appeared in the minds of Friends on my account,
I being of a very weakly constitution,
and brought very low through the great exercise of my mind;
but I was freely given up to the service,
and my trust and whole dependence was upon the Lord alone for wisdom, strength,
and preservation in every respect,
well knowing that he is all-sufficient for those who trust in him,
and are freely given up to do his will.

The 30th day of the fifth month, my friend John Bell, of London,
being lately returned from his travels in Holland, came to pay me a visit,
and stayed our meeting next day; and on second-day morning, the 1st of the sixth month,
after having taken my solemn leave of my dear mother and divers Friends,
I set forward on my journey.
My friend John Bell accompanied me to Richmond, where I met my companion.
We were all at that meeting,
and afterwards my said friend took his leave of us and returned towards London.

My companion and I proceeded, and had meetings at Larkington, Raby, Darlington and Yarm,
where I felt the authority and power of Christ the Lord in an eminent manner,
and many hearts were reached and much tendered by the Truth, and overcome therewith.
My soul was filled with the goodness of God, and in humble thankfulness,
living praises ascended unto Him,
who had graciously answered my cry and fervent desires to the full that day.
Let my soul trust in Him forever.
We went next to Stokesley, Norton, Stockton, Shatton, Durham, Sunderland, Shields,
and Newcastle, visiting their meetings.
On second-day we came to James Halliday`'s in Northumberland,
and thence to Allenwick and Embleton.
We found the number of Friends very small in that country,
yet were comforted with them in their little meetings,
witnessing the promise of our great Lord to be fulfilled, for though but a few,
his presence being in the midst of us, we had comfortable times.

On sixth-day morning, we set forward from John Doubleday`'s towards Scotland,
and through hard travel and rough ways, we came that evening to Kelsey,
and lodged at Charles Ormston`'s; from whence we went to a Friend`'s house over the river,
and had a very good meeting with a few Friends.
Next day we had two comfortable meetings in Kelsey;
the number of Friends there was small, but many soldiers and others came in,
who behaved soberly, and were very attentive to Truth`'s testimony.

The next evening we reached Edinburgh,
and had a comfortable meeting at the house of
our worthy ancient friend Bartholomew Gibson,
with Friends and others, who behaved soberly.
We then crossed the Firth to Parton-crag ferry, and lodged at an inn.

Passing through Montross we came to Robert Barclay`'s at Ury,
and had a meeting with Friends there.
On seventh-day we had a meeting at Aberdeen,
and on first-day a very comfortable one at Kilmuck,
for the Lord`'s power was felt in a good degree to come over all;
the largest number of Friends in anyone place in that nation, we met with here.
In the afternoon we had a meeting at Inver, Ury, where many people came,
who were very sober and attentive.
The Gospel of life and salvation was freely preached to them,
and I found much room in the people`'s minds to receive the testimony;
for which my heart was humbly thankful to the Lord,
who was graciously pleased to favour us with his power and living presence,
and enable us to give him the glory.

After the meeting we went to Awarthis, to the house of John Forbes, a good Friend,
a living minister, and a generous open-hearted man,
where we were received in much love and friendship;
but having rode that day upwards of twenty miles,
and had hard service in those two large meetings,
though I had great peace and comfort of mind, my natural strength was so much spent,
that it was with difficulty I sat upon my horse to the end of my journey.
We had a comfortable meeting in that honest Friend`'s house with Friends thereabouts;
and having stayed there two nights, and recovered my natural strength in a good degree,
we returned to Aberdeen, where we had a meeting the day following.
Next morning we had a very comfortable meeting at the widow Hall`'s house,
with Friends that came to see us, and we parted in much love and nearness.

We came to Kingswells, where our worthy friend Andrew Jaffray lived,
and had a very comfortable meeting with Friends,
and next morning a sweet and edifying season with those who came to take leave of us.
Though Friends in these parts were not numerous,
yet I was sensible many of them loved the Truth,
and in the love of Christ we were made near one unto another.
Notwithstanding it was my first visit and in the time of my youth,
I then believed it would also be my last to that country;
and during my stay amongst them, my soul was in a deep travail before the Lord,
for their preservation in the midst of a dark professing people.
We came next to Ury, then to William Neeper`'s near Montross,
and also to the town of Montross, where we had meetings.

Then turning our faces towards Edinburgh, we reached Parton-crag ferry that night,
and lodged at an inn.
Next day afternoon we got to Gingorn,
and went on board with our horses in one of their little vessels,
in order to cross the Firth.
There embarked in the same vessel a man of quality, with divers women in his company,
his chaplain, musician, and a considerable number of attendants.
They behaved themselves very rudely, making us the objects of their ridicule,
the chaplain being the rudest of any of them.
The gentleman himself was the only person who behaved with common civility;
the women sung, and the musician played, but we sat in quietness of mind,
and said nothing in reply to the many banters they put upon us.

In a little time the wind arose high, and being contrary,
drove the vessel towards the sea,
and the boatmen laboured hard to keep her up against the wind and waves, but told us,
they feared we should all be lost.
Their jollity and mirth then departed, and they were turned into sadness and mourning,
being surrounded with great fear and terror.
The chaplain went to prayers,
and my heart being filled with holy zeal against such hypocrisy, when he had done,
I told him, He was not in a fit condition for that great duty;
for the prayers of the wicked are an abomination to the Lord;
and then had a convenient opportunity to rebuke them sharply, and clear myself of them.
The chaplain replied, If they perished, we must die with them.
I told him, we had peace of mind, and knew where to retire,
the fear of death was taken away from us, and we were resigned in the will of God;
and if he saw meet that we should lay down our lives with such a rude company,
yet his Spirit bore witness with ours, that we were his children,
and he would receive us into glory amongst the spirits of the just.
The gentleman himself agreed with me, saying, If their lives were saved,
it would be for the sake of these two good women,
and rebuked his chaplain severely for his unbecoming behaviour.
Through the mercy of God, after about seven hours toil in that short voyage,
we landed safe at Leith, where they took up their quarters;
but as we intended for Edinburgh, and the night being very dark,
the gentleman sent two of his servants to conduct us safely to our lodging,
where we arrived in true thankfulness to the Lord,
whose preserving arm had been as a wall about us in all our difficulties.
He also sent next morning to inquire of our welfare,
and I returned a suitable acknowledgment for his favour and kindness.

The day following we had a meeting, to which many came who were sober and attentive;
but towards the latter part of the meeting,
while my companion was concerned in testimony, some came in who were rude,
and threw stones at us into the meeting, one of which had nigh hit my companion; however,
they did not much harm, for we had a good meeting.
Passing to Borrowstoness, we had a meeting at the house of Daniel Hamilton,
with Friends of Linlithgow and thereabouts.
On seventh-day, in our way to Garshore,
many people who were at harvest-work in the fields,
inquired where we intended to have a meeting next day; telling us they had no minister,
and had not heard the word of God preached for many weeks.
We told them we intended to have a meeting at Garshore; they said they would come,
and on first-day morning abundance flocked thither;
and Friends concluding their meeting-house was too small to accommodate them,
agreed to have the meeting without, which was very large, solid and quiet.
The Lord was with us,
affording us wisdom and strength to preach the Gospel freely to them,
in the power and demonstration of his own Spirit; a comfortable season we had,
for the power of Truth came up into dominion over all,
and we had great peace and satisfaction,
and in humility rendered praise to Him who is worthy forever.
After the meeting we went into an ancient Friend`'s house, who said.
He had not seen such a meeting there, since George Fox was in that country.

We went from thence to Glasgow, and had a meeting in their public meeting-place,
where the people were exceedingly rude.
They threw stones and dirt amongst us, broke the windows,
and made a very great noise whilst my companion was preaching.
I sat quietly waiting upon the Lord,
not expecting to have any thing to say to such a rude multitude,
but a concern coming upon me, I stood up sometime before I spoke,
in which interval they looked stedfastly upon me, and desired one another to be quiet,
that they might hear what I had to say.
I then spoke to them in this manner:
We are come from another nation in the love of Christ to visit you,
and at our return it is likely they will inquire of us,
concerning the people of Scotland: and what shall we say,
but that you are high in notion and profession of the Christian religion,
but in conduct and behaviour worse than the heathen? You are a reproach to your nation,
a shame to your teachers, and the more moderate magistrates of your country;
if you knew any thing of the Christian religion, you would show it forth.
They remaining quiet, I proceeded and cleared myself according to the ability then given.
We had a good meeting, and the Lord shall have the praise,
who owns his sincere children in all their exercises and difficulties.

But afterwards, not finding ourselves fully clear of that place,
we remained under a weighty concern and deep travail before the Lord,
that he might open our way to obtain peace, and to the glory of his name.
After some time we went to visit some Friends in their families, and in our return,
being about the time of their evening service,
the sound of their prayers on every side reached our ears as we went along the streets,
and struck at my very life,
in consideration of the great deceit and hypocrisy of that poor mistaken people.
My concern grew weighty upon me, and the distress of my mind very great,
not seeing which way to get an opportunity to discharge myself;
when we came to our lodgings I retired alone.
We lodged at an inn kept by a Friend, an honest man,
who not insensible of the concern we were under, proposed to my companion in my absence,
to have a meeting in his house that evening,
telling her he could lay several rooms together,
that would accommodate a great number of people.
To which she readily agreed, provided I was willing; and acquainting me with it,
I readily joined with her proposition, which afforded ease to my mind.
About the time appointed, many people flocked in,
and amongst the rest a considerable number of the collegians, with some of their heads,
who, we were afterwards informed, had an intention to oppose our ministry,
and dispute with us.
But the Lord was near to us, and gave wisdom and strength:
and I may say in great humility and nothingness of self,
the Gospel of life and salvation was freely preached to them,
in the demonstration of the Spirit and power,
according to the measure of the gift then received.
A very large assembly we had,
and our intended opposers stood directly before us like men chained.
Truth came over all, the meeting was solid and quiet,
and we had a good opportunity to clear ourselves.
The meeting ended in a solemn manner, the people dispersed peaceably,
and we rejoiced in a sense of the great love and favour of God,
who was graciously pleased to condescend and own us, poor creatures,
in a time of great distress; for which, and all his mercies, let him have the praise,
for it is his own work, and can only be carried on by his power to his glory.

After this, we had meetings at Hambleton and Cumberhead;
and finding ourselves easy to leave that nation, we set forward for England,
and in two days came into Cumberland, to a Friend`'s house at Jenkins-town.
We were humbly thankful to the Lord when we got safe there.
The people being very honest Friends,
kindly received us after our tedious and fatiguing journey.

In this county we visited the meetings at Sowpart, Sykeside, Egletonby, Scotby, Carlisle,
Moorhouse, Wigton, Hartley-hall, the Holme, Pardsey, Crosfield, Broughton,
and Cockermouth; and then left Cumberland, having been much comforted among Friends,
and had several large and good meetings;
for we found a great number of sincere sensible Friends therein,
and many faithful elders yet living, whose service was great, and by whose care,
through the help of Divine Providence, things were kept in comely order in the church.

We then proceeded to Hawkshead, Crook, Windermere, Graithwaite, the Height, Swarthmore,
Kendall, Grayrig, Dentstown, Wensleydale, and Garsdale; where we had meetings.
At the last place I left my companion to go to her own home,
we having travelled together this long journey in much love and true unity,
always being willing, according to the strength given,
to help to bear one another`'s burdens,
and in an humble sense of that Divine goodness we had been favoured with,
we look leave one of another and parted.

It hath ever been my inclination,
the little time I have been concerned to travel on Truth`'s account,
and hitherto it hath been my practice,
to make choice of an elderly experienced Friend for a companion;
and the help and benefit I have found in it,
engages me to recommend it to all young ministers.
Having met with our worthy friend Thomas Chalkley, who intended for our county,
he undertook to accompany me home.
We took Bentham meeting in our way, and the next day being seventh-day,
reached my mother`'s house; she rejoiced at my safe return,
which was in much peace of mind;
and I bless the worthy name of our great and good Master,
who is with his bowed down children;
we have great cause to serve him freely with all our strength,
for he is a rich rewarder of all his faithful followers.

After my return, being but weakly through hard travel and close exercise,
I continued at home, except sometimes visiting a few neighbouring meetings,
as I found my mind engaged.
The spring following,
my friend John Bell and I came to a conclusion to accomplish our intended marriage,
and it was with great awfulness and reverence,
having a due regard to the peace and freedom of my own mind,
that I consented to enter into a married life.

After a regular proceeding, according to the good order settled amongst us,
on the 31st day of the third month, 1710,
a large assembly of Friends and others met at our meeting-house at Bradford,
and the Lord in mercy was pleased to be near to us,
at our entrance into that solemn covenant, and a quiet solid time it was,
notwithstanding the great crowd present;
for many of the chief inhabitants of the town came, to whom I was well known,
who had not seen any of our marriages before.
The whole was managed orderly and with great solemnity.
The lawyers and most of the gentry signed our certificate,
and very much commended our method.
The chief lawyer in those parts went home with us, amongst others,
and said publicly in the company,
Our method and the manner of accomplishing our marriages, was the most solemn,
and preferable to all the methods of marriage in the world.

I tarried at home with my husband some time;
and when I found my mind engaged to visit Friends in the east part of our county,
acquainted him therewith; to which he freely consented.
On the 1st day of the sixth month, I set forward; my husband accompanied me to Stockton,
where I met with my cousin Rachel Bell,
who was come thither with an intention to be my companion.
We had a good meeting with Friends there, and next day went towards Gisbrough,
and had a meeting there on first-day.
Thence we came to Stokesly, where my husband left us, and returned home;
we had a meeting with Friends there, also at Bilsdale, Kirbymoorside, Rowsby, and Whitby.

From thence we travelled to Stantondale, Scarborough, Pickering and Malton,
having divers comfortable meetings; and so to Bridlington, Shipsey, Owstwick, Hull,
Eastend, North Cave, and Cottness,
and visited all the meetings of Friends along the east coast; and thence to Selby, York,
Wetherby, and Leeds.
Then finding myself clear, I left my companion there,
and got home to my dear husband and mother the last day of the same month,
and found all well.
We were comforted in the love of Christ, and my soul was deeply bowed before the Lord,
in a sense of his mercy, rendering all praise to him, to whom it is everlastingly due.

I continued about home that autumn and the winter following,
and in the spring fell into a weak condition of body, which brought me very low;
but when the summer came, finding myself in some degree recovered,
and having a concern upon my mind to visit Friends in Lancashire and Cheshire,
I acquainted some Friends with it,
who were much concerned at my taking a journey in that weak condition;
but when they understood my husband inclined to accompany me, it made them easy.
We had a certificate at our Monthly Meeting,
and set forward the 30th day of the fourth month, 1711,
and got to Wycollar in Lancashire, that evening, and next day to Trawden meeting,
where we had a comfortable time.
The thirdday following we set forward for Lancaster Quarterly Meeting,
where there was a large appearance of Friends,
and we had a very comfortable season together;
the Lord`'s opening power and presence being waited for,
was felt to lead Friends into their several services.
The church was edified, and humble praises ascended to the great Master of our assemblies.

After that meeting we went to Yelland, next morning to Kendall Quarterly Meeting,
and had a precious season.
We then visited the meetings at Hawkshead, Swarthmore, and the Height,
and returned by Yelland and Lancaster.
On seventh-day we came to Richard Coward`'s, in the File country,
and had a meeting appointed at Stammen;
it was held in a great barn over against the parish worshiphouse:
the meeting was large and crowded, the people quiet and very attentive,
and we found room for the testimony of Truth amongst them.
The Lord was with us, furnishing wisdom and strength,
which enabled us to preach the Gospel of glad-tidings; the meeting ended well;
Friends were comforted in our visit, and we truly thankful unto the Lord,
who had enabled us to publish his Truth and show forth his glory.

We went thence to Clifton, and Coppel, where we had a very comfortable meeting.
Here we met with our worthy friend John Haydock, and went with him to his house;
he was free and fatherly, glad of our visit, and accompanied us to divers meetings;
his conversation was solid and edifying, as well as affectionate;
we were comforted and encouraged in our service by his company,
and parted in much love and nearness.
We came next to Hardshaw Monthly Meeting,
then proceeded to visit the meetings at BiggerstafF, Liverpool, Knowlsby, Sanky,
and Franly, in Cheshire; where, it being first-day, we had a large meeting.

At the breaking up of this meeting, I fixed my eye upon a young man,
and felt a concern upon my mind to go home with him,
but he got away out of the meetinghouse before I could speak to him.
We went into a Friend`'s house adjoining thereto, where many Friends came to us,
divers of whom earnestly entreated my husband to go with them for that night;
but he leaving that to my choice, they applied to me; I told them,
I had seen a young man in the meeting, with whom I inclined to go if I could find him.
They asked me, If I knew his name, or where he lived? I replied, I knew neither;
but during this conversation,
I saw him passing an entry which went through the Friend`'s house, and called to him.
When he came, I inquired of him where he lived? He said, about three or four miles off.
I asked him, If he could accommodate us with a night`'s lodging,
if we should incline to go with him? He answered, Yes, and should be glad of our company.
I then became easy, and we went along with him.
When we came to the house, we found them a family of honest Friends,
but his father in a very low dejected frame of mind.
I said little to him, but concluded to have a meeting in the family that evening,
and a glorious opportunity it was,
for the power of Truth broke in upon us in a peculiar manner,
and the ancient Friend was much reached, comforted and strengthened in his mind,
and as I was afterwards informed, was never so much overcome with that weakness any more.

This passage I mention with no other view,
but that all Friends who travel on Truth`'s account, may diligently wait upon God,
and strictly mind their guide, to be opened by his counsel,
and rightly led into all their services,
both as to what meetings and families they are to go to,
for in this I have found safety and comfort.
The work is the Lord`'s, and we had need to depend upon him,
and diligently wait for the immediate motions of his holy Spirit,
for it is by his own power only that his servants are
fitly qualified to be serviceable in his church,
rendered a comfort to his people wherever they come,
and enabled to discharge themselves faithfully to his glory; and when we do so,
the inflowings of peace will be our abundant reward.

We proceeded on our journey to Norton, Middlewich, Newton in the Forest, and Chester,
visiting the meetings of Friends, and to Nantwich meeting, to which many people came,
not of our profession, who behaved themselves soberly and attentively,
divers being reached; for the power and good presence of Christ was with us.
As a fresh concern came upon me to visit Friends in North Wales,
we in great humility deliberately considered the thing,
and in freely giving up to the motion of life, found peace;
and our way being clearly opened unto us, we returned back towards Chester again,
and came to Wrexham, in Denbigshire,
where we had a good meeting with the few Friends there; and then to Dolobran,
where we had a large meeting, and though it was through hard exercise,
it proved in the end very satisfactory to us and Friends.

The next evening we got to Ballough, and the day following being first-day,
had a meeting about two miles out of the town, at the house of Robert Vaughan.
We found the number of Friends very small, but loving and glad of our visit.
Next morning we set forward early,
and had a long day`'s journey over the mountains to Dolgelly,
but came safe at night to the house of Ellis Lewis, who received us kindly,
and we had a good meeting there next day.
After this we went to Humphry Owen`'s, who lived by the sea side,
and the day following had a comfortable meeting at his house,
with the few Friends thereabouts.
Next morning we proceeded,
and had a large and very good meeting next day at the house of the widow Bember.
Here we found a considerable number of Friends,
and divers who had a little time before been convinced of the Truth,
and joined with Friends; we were highly favoured amongst them,
for the power of Truth came up into dominion in a great degree;
the hearts of the people were melted like wax before the fire,
and the young convinced much comforted and confirmed in the blessed Truth,
in a sense of the love of God to them; we were also comforted with them,
and high praises were given unto God for his blessed
visitation renewed to his people that day.

On the first-day following we had a meeting appointed at the house of William Sawley,
there being divers convinced in that part of the country;
many Friends met us from several distant parts where we had been,
and a number of other professions being gathered together, we had a large assembly,
and a full and good opportunity amongst them,
great openness appearing to receive the Gospel.
After the meeting we parted with them,
and in particular with our worthy ancient friend Robert Griffith,
who had accompanied us from Dolobran during our stay in Wales,
and been of great service to us.

Leaving Wales we came into Shropshire,
and visited the meetings there and some in Cheshire; then finding ourselves clear,
we pursued our journey homewards, and came to Bradford,
where we found my dear mother and all things well, for which we were humbly thankful;
and in the enjoyment of that peace which we were
filled with in obeying the Lord`'s requirings,
and serving him faithfully, we were made to rejoice and bless his name.

Being but weakly at my setting out,
I found myself much spent when my service in that journey was over;
and notwithstanding I had been wonderfully supported and strengthened,
I found liberty to tarry about home the remaining part of this year;
during which time there was a particular
visitation of truth to the people about Keighley,
and many flocked to Friends`' meetings in that town.
My husband and I found ourselves often concerned to visit them,
and divers being convinced, joined with Friends.

About this time, a young woman who was a baptist,
came divers times to a meeting I sometimes visited, and wrote several letters to me,
by way of inquiry concerning our principles,
which I answered as things opened upon my mind.
After several letters had passed between us and she seemed satisfied with my answers,
she wrote me another, desiring to be resolved about women`'s preaching, saying,
she thought me a proper person to apply to, being concerned in that service;
to which I replied in substance as follows.

[.embedded-content-document.letter]
--

[.salutation]
Dear friend,

Though we are strangers one to another, as to personal knowledge,
yet understanding by some friends, and thy own letters to me,
that thou art inclined to virtue and piety, and desirous to know the way of the Lord,
which is very commendable in youth,
and particularly wants to be resolved concerning women`'s
preaching and praying in public assemblies;
and I being concerned that way,
and always glad to hear that young people are inclinable to godliness,
find the tender love of my heavenly Father flow towards thee,
heartily desiring he may open thy understanding,
and give thee the true knowledge of himself, and of his way Christ Jesus,
whom to know is life everlasting.

And first I shall observe, that the holy women, under the law,
were concerned in carrying on the work of the Lord,
when the tabernacle was commanded to be built.
And Moses spake unto all the congregation of the children of Israel, saying,
this is the thing which the Lord commanded, saying,
take ye from amongst you an offering unto the Lord, whosoever is of a willing heart, etc.
And they came every one whose heart stirred him up,
and every one whom his spirit made willing,
and they brought the Lord`'s offering to the work of the tabernacle of the congregation,
and for all his service, and for the holy garments; and they came both men and women,
as many as were willing-hearted, etc.

And all the women, whose hearts stirred them up in wisdom, spun goats hair, etc.
And divers services we may find, for the carrying on of the Lord`'s work,
the holy women in that day were employed in assisting in
concurrence with the men in the work of the tabernacle;
which I look upon was figurative,
setting forth something of the inward work of the holy spirit of Jesus Christ,
in men and women under the glorious Gospel dispensation.

But to come closely to the point, we may observe, that Miriam the prophetess,
the sister of Aaron, took a timbrel in her hand, and all the women went out after her, etc.
And Miriam exhorted them to praise the Lord; which undoubtedly was approved by Moses,
Aaron, and the rest of her brethren.
We also find,
the Lord hath been pleased to make known his will to godly women as well as men,
and to make use of their service in matters of great moment;
of which Deborah a prophetess and a judge in Israel, and Huldah, the prophetess,
are eminent instances.
Hence thou mayest see, the public service of women in the church is no new thing,
but was practised amongst the people of God in ancient days.

I shall now proceed to observe, that the same was to be continued in the latter days,
or dispensation of the Gospel; which is thus expressed by the prophet Joel,
personating the Almighty: '`And it shall come to pass afterward,
that I will pour out my spirit upon all flesh,
and your sons and your daughters shall prophesy, etc.
And also upon the servants and upon the handmaids in
those days will I pour out my spirit,
and I will show wonders in the heavens and in the earth,`' etc.
So if daughters have the Spirit of the Lord poured forth upon them, as well as sons,
why may they not preach, pray, or prophesy, when led and moved thereto by the Spirit,
as well as sons?

Passing now from the Old Testament to the New,
we find a notable instance in Anna the prophetess,
who gave thanks and spoke of the Lord Jesus Christ unto
all them who looked for redemption in Jerusalem.
Here was a woman preacher, who taught or prophesied in the temple of the Lord;
an early preacher of the Son of God, the Saviour of the world.
But I suppose the chief objection in thy mind against women`'s preaching,
arises from that saying of the apostle Paul in his first epistle to the Corinthians;
'`Let your women keep silence in the churches: for it is not permitted unto them to speak;
but they are commanded to be under obedience, as also saith the law.
And if they will learn any thing, let them ask their husbands at home:
for it is a shame for women to speak in the church.`' It
appears to have been only to some married women at Corinth,
the apostle gave that charge; and none can justly draw from his words,
that he thereby meant to prohibit all women from
preaching and prophesying in public assemblies;
for it is plain from the text, that those Corinthian women were not such as prophesied,
or had a word of exhortation to give; but busy-bodies,
asking questions which disturbed and troubled the church.

But those amongst us, whom the Lord has concerned to preach the Gospel of Jesus Christ,
and declare the glad-tidings of life and salvation by him, to poor captivated souls,
are not found asking questions to trouble the church;
but labouring in the gift God has given them,
that people may come to be turned from darkness to light,
and from the power of Satan to God;
which was the concern of Gospel ministers in former days.
Such women as the apostle speaks against, were to learn of their husbands at home;
which implies, they wanted such instruction as their husbands might be able to give.
We read, Philip had four daughters, virgins, who did prophesy,
and though Paul and his company tarried there about a
year after he had so written to the Corinthians,
yet we do not find,
that he in any wise disapproved the prophesying of those godly virgins.
We may justly conclude,
that if women`'s preaching or prophesying had been put an end to by the coming of Christ,
and was not to be allowed in the Gospel dispensation, Philip, an evangelist,
would not have suffered his own daughters to prophesy,
who were virgins under his own care, as may reasonably be supposed.
Nor did the other apostles, in their general epistles to the believers,
give any such commandment to the churches; which, no doubt, they would have done,
if in the Gospel dispensation the Holy Ghost had prohibited women being so concerned.
Besides,
such a prohibition would have been a plain contradiction to the prophecy of Joel,
before mentioned.

It also appears very clear, that the apostle Paul never intended such a limitation,
who gave suitable advice how women should behave
themselves when exercised in praying and prophesying,
as thou mayest read.
They that conclude the apostle intended to
exclude all women from praying and prophesying,
make him inconsistent with himself,
to prescribe a way in one place how to perform orderly and decently,
what he disapproved in another.
But the same apostle is very clear when he saith,
'`For as many of you as have been baptized into Christ,
have put on Christ.`' '`There is neither Jew nor Greek, there is neither bond nor free,
there is neither male nor female;
for ye are all one in Christ Jesus.`' Then if
there be no difference between male and female,
but all are one in Christ, why may not all be like partakers of the gift of his grace,
thereby to be made to speak in his name,
and exhort all to believe in him and obey him? And it is likewise to be observed,
that in the same chapter the apostle advised the
women at Corinth not to trouble the church,
he saith, '`Ye may all prophesy one by one, that all may learn,
and all may be comforted.`' From whence it may be as strongly argued,
the apostle meant they might prophesy, though not required of them by the Lord so to do;
as to say he forbad women to prophesy, though the Lord required it of them.
For saying '`You may all prophesy,`' included the women of Corinth as well as the men,
if moved thereto by the Spirit of the Lord.
And though the apostle saith, '`Let the women learn in silence with all subjection,
but I suffer not a woman to teach, nor to usurp authority over the man,
but to be in silence,`' etc.
Respecting this I shall observe, that those women,
upon whom God hath poured forth of his holy Spirit,
and filled their hearts with his living word, so that they cannot hold their peace,
but a necessity from the Lord is upon them to preach the Gospel of glad-tidings,
to those who are captives to sin,
that they may come under the government of the law of the spirit of life,
that sets free from the law of sin and death,
having been made living witnesses of the work of God in their own hearts,
and experienced a blessed change wrought therein,
and a concern raised to call others to seek after the Lord, and fear him;
these can direct into the way that leads to true peace,
because they have known their feet to be turned into it,
by the mighty arm and power of the Lord,
which has wrought a willingness in them to follow and serve him,
according to the ability he gives.
And this agrees with that saying,
'`Thy people shall be willing in the day of thy power.`' And he has, by his power,
enabled a remnant to walk in his way, though a way of self-denial, step by step;
and these, whether men or women, have witnessed a learning in silence,
as they have thus waited and rightly come to learn of Christ Jesus,
their heavenly husband; he has opened his everlasting way and Truth unto their souls,
and even constrained them, by his overcoming love, to declare of it to others,
which has been done at times in fear and trembling, and much self-denial.
Such women are not of those the apostle had occasion to reprove.
For we are far from usurping authority over the men, but remain in true subjection,
depending upon the Lord our strength, and waiting for the authority of his holy power,
which calls to this great work, and carries it on, both in sons and daughters,
to the praise of his great name, and the comfort and encouragement of poor longing souls,
that they may come also and enjoy for themselves,
that which will nourish up unto everlasting life.
Such women as these the law allowed of, and the apostle allowed of,
as might be more fully proved out of the holy Scriptures.
For they who allow not women`'s prophesying, preaching or praying,
must consequently conclude, that the Lord`'s regard to them is lessened,
and his love in measure withdrawn from them; for it is evident,
by the texts I have mentioned, he made his mind known to women in ancient days,
and they spoke in his word to his people; and as their counsel was taken,
the Lord enabled his people to overcome their enemies.

But blessed be the name of the Lord, there is a remnant in this day,
who have been made partakers of his mercy, and can say he is the same that ever he was,
in regard and love to all his people, male and female; God unchangeable,
blessed in himself and in his Son Jesus Christ forever.

I might enlarge on this subject beyond the bounds of a letter, should I observe,
how Jesus Christ our Lord conversed with,
and used the service of women before he was offered up; how his first appearing,
after his resurrection, was unto a woman; and also how Paul commended divers women,
and tells how helpful they were to him,
and entreated his true yoke-fellow to help those
women who laboured with him in the Gospel;
which for brevity I omit, and shall draw towards a conclusion,
earnestly desiring the Lord may open thy understanding, both in this thing,
and in all others which concern thy everlasting well being.
If I had room,
I should be willing to tell thee a little of my own experience in several respects,
but am more desirous to have a little conversation with thee, if opportunity admits.
So with sincere desires in my heart, for thy welfare and growth in the knowledge of God,
and establishment in the blessed Truth, I conclude thy truly loving friend,
willing to satisfy thee in what I can.

[.signed-section-signature]
Deborah Bell.

--

A considerable time after, this young woman came to a meeting where I was,
and when it ended, told me she was the person who had written me divers letters,
and received my answers, desiring to have some conversation with me,
which I readily agreed to, and we spent some hours together to our mutual comfort.
She confessed to the Truth,
and was much tendered through the visitation of the love of God to her;
and some time after, finding my heart opened in the love of God,
earnestly desiring her preservation and settlement in the Truth,
I wrote and sent her the following letter.

[.embedded-content-document.letter]
--

[.salutation]
Dear friend,

In the love of my heavenly Father, I dearly salute thee, earnestly desiring that peace,
which passes the understandings of men, which the world can neither give nor take away,
may plentifully abound in thy heart, which no doubt will,
as thou comes to yield sincere obedience to that of God in thy own conscience,
which thou art in some measure acquainted with,
as it hath manifested to thee several things which are contrary to the will of God;
and not only so,
but hath likewise let thee see what thou shouldst do to obtain peace in thy soul;
and that which is required of thee is, that thou obey, from the bottom of thy heart,
the manifestations thereof.
Though at first it may seem to be but a small light, shining in a dark place,
discovering those things that are evil to the soul;
yet as there is a diligent attention to it, it will shine brighter and brighter,
and discover more and more, till everything that is evil be manifested thereby;
and in due time, thy soul will come to a perfect knowledge of the will of God,
and experience that the path of the just is as a bright and shining light,
which shines more and more until the perfect day.

Dear heart, I know the love of God is largely extended to thee,
and he has blessings in store for thee,
if thou wilt but wait to be so wrought upon by his heart-changing power,
as to be made fit to receive them.
I do earnestly entreat of thee, as thou desires peace of conscience,
and a resting place in eternal joy for thy soul,
that thou beware of doing or joining with any thing that brings trouble upon thee,
and breaks thy peace with the Lord.
Be sure to mind what makes for thy peace, and that do;
though it may be through hard exercise, and under the cross.
This is the right way that all God`'s faithful
children and people have trodden in all ages;
and truly, it seems to me, that thou must have a great share of the cross to bear;
but be not discouraged at this,
for it is but a cross to that part which never can inherit the kingdom of heaven.
So that it is for the benefit of our souls,
to have that part crucified and slain which is an enemy to us,
and would hinder us from entering into eternal felicity;
and I have further to say for thy encouragement,
that those who have the greatest share of exercises and tribulations, shall,
if they abide stedfast,
receive a more exceeding recompense of joy and consolation of soul from the Lord.

Dear child, keep true in heart unto God, and eye him above all,
who hath been so large in his love, as to work upon thy heart by his power,
in thy young and tender years.
It is in order that thou mayst be made a fit instrument in his hand,
for the glory of his holy name;
and I believe he will carry on his work gloriously in thy soul,
as thou art truly obedient, and subject to his workings there,
even to the filling of thy heart, not only with admiration of his dealings with thee,
but also with great reverence and thankfulness to him, for his mercy and goodness.

My pen is not able to set forth one half of the comfort those enjoy,
who are given up in heart to follow the Lord fully,
and turn their backs on all the glory of this perishing world;
but thou shalt be a witness thereof thyself in the Lord`'s time,
if thou truly loves him above all, and denies all for his sake.
Therefore, I beseech thee, take care of resisting the good Spirit of God,
whilst it is striving with thee; for this is the day of thy visitation,
wherein life and death are set before thee; and the Lord will not compel any,
but he offers his love freely to all; and forever happy wilt thou be,
if thou joins in with it.
But on the contrary, if thou looks out at the glory of the world,
and prefers it before peace with the Lord,
or looks at the exercise and difficulties thou mayst have to encounter withal,
and art thereby prevailed upon to let thy spiritual concern drop,
it had been better for thee thou hadst never known the mind of the Lord,
nor had his will manifested unto thee.
I can tell thee by experience, that God is no hard Master;
and though many things appear to us, that may seem impossible to be overcome,
yet as our eye is to the Lord, with sincere desires in our hearts to answer his will,
we shall find he is all-sufficient to support and enable to overcome.
Nothing is too strong for him,
though all the powers of hell combine together against him,
to hinder his work from being carried on in the soul.
If the soul dwells but under the government of his holy power,
and waits for his heavenly teachings, from whence Divine wisdom cometh,
which wisdom the Devil with all his subtlety can never beguile;
such from experience shall have cause to say,
the power of God is above all powers whatsoever.

O cleave close to the Lord, and he will never forsake thee,
nor be wanting for thy help in the most needful time of trouble.
But let me say once more, take heed of slighting this the day of God`'s love, or delaying;
for thy soul is at stake, and thou mayst never have the like visitation again.
I have been very much concerned for thee,
and have suffered in spirit with thee since I saw thee, and it is for no by-ends at all,
but for the discharging of my conscience of that duty I owe,
and in pure love to thy never-dying soul, that I send these lines,
heartily desiring they may have the desired effect upon thee;
and I believe the day will come, wherein thou will be made sensible,
that it is in the love of God these lines are written.
I shall now draw towards a conclusion, having enlarged beyond what I at first intended;
for I find my heart opened in love to thee,
and shall remain one who travails for the good of souls,
and that many may be brought into true acquaintance with the living God,
and know their peace to be made with him, before time to them here shall be more.

[.signed-section-signature]
Deborah Bell.

--

Having felt drawings in my mind for some time,
to visit meetings in the southern counties of England, and the city of London,
the spring following, I acquainted Friends with it, and had a certificate.
Rebecca Cowell offered to be my companion, and on the last day of the first month, 1712,
we set forwards, and had meetings at Balby, Blyth, Collingham, Swinehead, Spalden,
Gedney, Wisbich, Upwell, Lynn, Fakenham, Wells, Holt, Lammas, and Norwich;
where I was kindly received, particularly by our worthy friend John Gurney, senior,
who was an intimate acquaintance of my dear father`'s,
and he related to me many affecting passages of his labours
and service in that city and county in early times.
During our stay there, his fatherly care over me was very engaging,
and I believe will never be forgot whilst my memory is strong enough to retain it.

We had a meeting in that city on a weekday; then went to Yarmouth,
and had a meeting with the few Friends there; but not being fully clear in my mind,
I parted with my companion and came back to Norwich, and stayed the first-day meetings,
which were very large: I had a good time amongst them, and we were comforted together.
Next morning we parted in a sense of the love of Truth, and I came to Taisbrough meeting,
where joining my companion again, we visited the meetings at Tivetshall, Diss, Thetford,
and Ixor.
Then leaving Norfolk, we went to Bury, and were at the meetings there on the first-day,
where many people came in.
We had a good opportunity amongst them, for Truth owned us in our service;
for which my soul is humbly thankful unto our great Lord and Master.

From thence we went to Mildenhall, Bayton, Mendlesham, Needham, Woodbridge, and Layson,
visiting those meetings;
and at the last place had a good and comfortable
season amongst a tender inquiring people.
We also found a sober tender people at Branston, and had a good time amongst them.
We then proceeded to Walton, and Ipswich, visiting their meetings.
Then leaving Suffolk, we visited Friends at Colchester, Birch, Kelvedon, and Chelmsford.
On the 16th day of the third month we reached London,
and went through all the meetings in that city, where we had many precious seasons.

The Yearly Meeting drawing on, my husband came up and met me there,
where I saw many of my worthy friends, and had comfortable meetings with them.
After which, my mind being clear and fully easy, I parted with my companion;
and my husband and divers friends accompanying me, we left that city,
and taking a meeting at Albans, we proceeded homewards, where we arrived safe,
and found my dear mother and all well.

I enjoyed great peace in giving myself freely up to the service of Truth,
and humble thankfulness remained on my mind to the Lord for his mercy,
in granting a sense of his living presence and power to
the support and comfort of my exercised soul,
in all my travels for promoting the Gospel.

My husband having been inclined for a long time to remove to London,
the place of his former residence, had proposed it to me,
and left it under my consideration, where it remained for some years;
he leaving it with me without the least importunity.
It was a serious thing to me, and I often besought the Lord to know his will therein;
for I considered I was the only branch of the family
left to come up in my dear father and mother`'s places,
in their divers services in the church, greatly desiring I might not miss my way;
and great fear was upon my mind.
My heart was sincere before the Lord; and in process of time,
patiently waiting for the counsel of God, I saw the way clearly,
and had a certain evidence that the Lord would be with us,
and own us in that undertaking.
This removed all doubts, and I freely consented.
We then acquainted Friends with our intention; upon which they were much concerned,
for we had a place amongst them, they thinking us of service;
and also being cautious lest we should miss our way, were very loth to part with us;
however, after divers consultations, they left us to our liberty.
We prepared for our removal,
and about the middle of the seventh month set forward for London,
brought my dear mother along with us, and settled in the city.

Being afterwards drawn in my mind to visit Friends in Kent,
the 31st of the tenth month 1715,
and having my dear friend Margaret Ollive for my companion, we visited the meetings,
and finding ourselves easy, came safe home, after a difficult journey though but short;
for the weather was extremely cold, being a hard frost and a deep snow,
during the whole time.
Upon coming home, our hearts were filled with thankfulness to the Lord,
who had accompanied us in our service, and preserved us from any harm.

A concern having rested upon my mind for a considerable time,
to visit some of the meetings of Friends in the north of England and Ireland,
which growing weighty upon me, I acquainted my husband and mother with it,
who readily consented to give me up to that service.
My former companion, Margaret Ollive, agreed to accompany me;
and having the consent of Friends, and certificates of their unity with us,
the 16th day of the twelfth month 1716, we set forward,
being accompanied to Albans by my husband and divers other Friends,
where we had a meeting that day; after which,
my husband took his leave of us and returned home.
We then proceeded to Market street, Newport-pagnel, Northampton, Braybrook,
Leicester and Nottingham, where we had meetings.
Thence we travelled directly to Bradford, in Yorkshire,
and had a very good open meeting amongst my dear friends and former neighbours,
who rejoiced to see me once more at the place of my nativity.
A very comfortable opportunity it was to many;
for which I was truly thankful unto our great Lord and Master,
and more and more confirmed that he is worthy to
be followed and obeyed in all his requirings.

From thence we went to Satterforth and had a meeting; then to Settle Monthly Meeting,
where we had an opportunity of seeing many of our friends from several meetings,
and had a comfortable time with them.
From thence we came to Kendal, where we had two comfortable meetings,
which strengthened us in our service, and the church was edified in the love of Christ.
We went next to Windermere meeting, and so to Cockermouth,
and it proving a very snowy day, and I being weakly,
was hard set to bear it over the mountains; however,
through the favour and protection of Providence,
we got that night to our worthy friend Peter Fearon`'s. His wife,
my particular friend and acquaintance from my childhood, received us kindly,
and her motherly care was great over us.

Next day we went to Pardsay meeting, and had a good time amongst Friends there;
after which we returned to our lodging, but the wind and snow were so very severe,
we could scarcely sit on our horses.
We stayed there four nights, the snow being so deep and the weather boisterous,
that it was judged very unsafe to travel.
On the first-day we had two very good meetings at Cockermouth.
Next morning leaving my companion with Friends there, I set forward towards Carlisle,
to visit my husband`'s father, and some other relations in that part of the county,
where I had divers comfortable meetings; and being much pressed in mind for Ireland,
intended to return to my companion in order to proceed in our voyage;
but the wind continuing contrary, and their Quarterly Meeting drawing on,
Friends persuaded me earnestly to stay that meeting.
On deliberate consideration, I found freedom in my mind to consent thereto,
the wind still continuing contrary.
The meeting being to be held at Carlisle, my companion met me there,
and many Friends came.
A large and good meeting it was,
being overshadowed with the power of Truth in a good degree,
though much disturbed by several who were
possessed with a ranting unruly opposite spirit.
But the governor of the city understanding how they disturbed the meeting,
sent his officers to take them away.
Next day they came again, and began to disturb the meeting as before,
but were soon carried away by the forementioned authority, only one John Robinson,
escaping the officers`' notice, continued in the meeting;
while a Friend was declaring the Truth, he sat still, but when he had done,
began to reflect upon Friends with railing accusations.
I being under a weighty concern stood up,
and in the dread and power of the Lord began to declare
of the free grace and universal love of God to mankind.
At which he cried out, Disorder; but a man of considerable note in that city,
commanding him to be silent, or he would take him out of the meeting, he sat down,
and I went on in the authority of the Lord`'s power,
my heart being filled with the love of Christ,
which flowed freely to that exercised people,
and the Gospel of life and salvation was preached to them,
and many hearts were reached and much affected with the Truth.
A glorious meeting it proved, and my soul was deeply bowed in humility before the Lord,
who owns his poor weak ones that faithfully serve him, in every needful time,
who shall have the praise of his own work.

When the meeting ended we took our solemn leave of Friends,
being near to us in the unity of the one spirit,
which makes the children of God truly one all the world over;
and a worthy ancient Friend said, when I took my leave of him, Heaven had favoured them,
in detaining us to attend that meeting; we now had stayed till the right time,
and they could freely part with us.
So we came away in perfect peace,
and were greatly comforted in a sense of the love of God;
for I never left that part of the country with so much ease of mind before.

We travelled twenty miles that afternoon to Cockermouth, and early next morning,
as the wind continued fair, we rode to Whitehaven, and finding the ship ready to sail,
went on board immediately, being the seventh-day.

We had a tedious passage by reason of contrary winds; and very mean accommodation;
however, through the favour of Divine providence,
we got safe to land on the fourth-day evening, and went to Dublin that night,
where we were kindly received by our friend Joseph Gill.
Next day we had a meeting in that city amongst the scholars in the school-room,
and on sixth-day a large meeting with Friends and others, in their meeting-house.
On first-day we had large meetings, where the testimony of Truth had free passage.
We were comforted one in another, and blessed the Lord,
who is making his people who abide in his own spirit, dear to one another,
of whatsoever nation they are.

We stayed about ten days in Dublin, and had seven meetings,
wherein we had good and comfortable opportunities; and leaving that city,
we went to John Barcroft`'s on a seventh-day; the day following to Edenderry,
and had two comfortable meetings; from thence to a place about seven miles distant,
where we had a meeting; thence to Mountmelick, and visited that meeting,
and had next a very solid meeting at Mountrath.
About four miles from thence we came to a widow woman`'s house,
where we had a very sweet and comfortable meeting, and returned back again to Mountrath.
We spent the seventhday in visiting Friends, divers of them sick.

Then visiting Ballynakill, and Kilconner, we came to Newgarden,
where the testimony of Truth went forth in a sharp and close manner,
against public disorder and secret sins; things were opened so clearly in my mind,
that I could safely have said,
"`Thou art the man;`" for the Lord is opening secret things to his faithful servants,
in this day as in days past; blessed be his name, saith my soul,
forever! for those that trust in him are helped by him,
and need not lean on the arm of flesh;
for nothing can do God`'s work but his own arm and power.

From thence we went to Ballitore and had a meeting,
and so to Castledermot to the province-meeting for Leinster,
and were at the meeting of ministers and elders,
where we were glad to see many of our dear friends and brethren,
and were sweetly comforted and refreshed in the Lord,
and one in another in the love of Christ.
Next morning was held a very large public meeting for worship,
wherein we had a good opportunity, and in the afternoon the meeting for business.
On first-day we had a very large meeting, the power of Truth was with us,
and I had strength given to discharge myself faithfully.
It was a satisfactory time, our elder brethren giving us the right hand of fellowship,
and prayers were put up to the Lord, for our help and prosperity in his work,
who is the giver of every good and perfect gift,
for they were sensible of the weighty concern we were under.
Indeed it is a very great thing to travel to
promote and publish the Gospel of Jesus Christ,
and loudly calls for the greatest humility, reverence and awe,
ever to remain upon the minds of all those concerned therein.

After meeting we returned in great peace towards Dublin,
and the day following there was a marriage,
and the greatest number of people together that I had ever seen on the like occasion;
a brave opportunity it was to publish the Truth,
and great openness I found upon my mind to that people,
and the Gospel of salvation was freely preached to them.
They were quiet and orderly, and many very attentive to the testimony of Truth,
who had never been at any of our meetings before:
others who had not heard a woman preach, went away well satisfied, and we were comforted.
We stayed in Dublin till the first-day following,
having several meetings amongst Friends in the mean time,
and on first-day had two very large meetings; for the Lord in his goodness and mercy,
was pleased to open things to their states, and we found our minds clear and easy.

On the third-day following began their Halfyear`'s Meeting,
wherein many living testimonies were borne to the comforting of the faithful,
and warning and stirring up the careless to more diligence and circumspection.
The meeting held several days, and the Lord, who had been with us in our public services,
was graciously pleased to own us in taking leave of one another,
to our confirmation and comfort, which was in a select meeting of ministers and elders,
seasoning our spirits with his love, in which we parted.
Being fully clear we left Dublin that afternoon,
and had a number of good meetings amongst Friends.
Many people came, and the Lord`'s power and good presence were with us in our service,
and we were much comforted in his love, and remained humbly thankful to him.

From thence we went to Coothill, and had two large meetings on a first-day;
many Friends living thereabouts, and divers sober neighbours coming in,
we had very open and comfortable meetings.
We travelled on to Ballyhagan, Old-Castle, and the Moate, and had satisfactory meetings.
At the last place was the province-meeting for Leinster,
where the testimony of Truth came up in dominion over all deceit and false shews,
and we had opportunities to discharge ourselves,
and came away with satisfaction and peace.
From thence we went to Waterford and Birr, and visiting the meetings,
came to John Ashton`'s, and had a meeting which was large, many people coming in;
there was great openness in that place to receive the testimony of Truth,
and some convincement.
We then proceeded to Limerick, where we had three meetings,
and the Lord was graciously pleased to give sufficient
ability to go through with the service in that town;
and having discharged ourselves faithfully, we came away in peace;
for which we were humbly thankful to the Lord, upon whom our whole dependence was,
and we were never disappointed.

We came next to Charly-field, were at that meeting, and thence to Cork,
where we stayed some time, I being reduced very low in my bodily strength,
through travel and close exercise, which was my lot in this journey,
brought on such infirmities as rendered me unfit for much more travel at that time.
We had divers large and good meetings in that city,
there being a considerable body of sensible zealous Friends.
After a few days we went to Youghal and Bandon, visiting the meetings,
and returned to Cork again.
After some stay there, my weakness increasing, I saw my way clear to return home,
but waited some time for a passage; we had divers precious meetings,
and often the company of our dear and worthy friend Joseph Pike,
and other ancient Friends then living, who were pillars in the church,
whose conversation was very comfortable, edifying and profitable to us.

A ship being ready to sail, we took our leave of Friends there in a solemn manner,
and in a lively sense of the goodness of God to his people, came on board;
we had a good passage, and in two days landed safe at Swanzey, in South Wales.
We then travelled to Bristol, where we met with our friend Joseph Ollive,
whom we were glad to see, he being come thither, in order to conduct us home.
We had several large and good meetings in that city, to ours and Friends`' satisfaction.
We then came to Bath,
and had two good meetings with the few Friends and others in that place;
from thence to Reading, where I met my dear husband and divers Friends from London,
who had come to meet us.
We had two meetings in that town, the last of which was very large,
and an extraordinary time; for the power of Truth came over all,
and we were much comforted in the Lord.

Next morning we set forward for London, got safe home that night and found all well;
for which I was humbly thankful to the Lord,
who had been pleased to call me forth from my habitation,
to visit his people in the nation of Ireland, and divers other places, in his service,
and hath been pleased to accompany me with his living presence,
whereby I was enabled to go through the work he required of me,
and have also been preserved through all dangers and perils, both outwardly and inwardly,
to his own praise and my comfort;
for which my soul is under deep obligation freely to follow him in all his leadings,
who is worthy forevermore.

Having a concern upon my mind again to visit some meetings of Friends in Ireland,
and to attend their Half-year`'s meeting, I acquainted my husband and mother therewith,
who freely consented to give me up to Truth`'s service; and having Friends`' certificate,
towards the latter part of the first month 1720,
I set forward in the stage-coach for Bristol,
and being there informed a ship lay at the Pill ready to sail,
and a young woman suitable to accompany me in that voyage was gone down,
in order to embark, I looked upon it as a providential opportunity;
so I hastened to the Pill that evening and met with her.
We lodged there that night, and next morning set sail with a fair wind;
but being afterwards becalmed, were six days in the voyage before we reached Cork,
where we arrived safely through Divine mercy,
and many of my dear friends and I were glad to see one another once more.

A few days after came on the provincemeeting for Munster,
where I had the opportunity of seeing many Friends from divers parts,
and Truth owned us in that meeting to our comfort.
I stayed in and about Cork twelve days, and had ten meetings amongst Friends and others,
some of which were seasons worthy to be remembered.

Leaving Cork I came to Kilconner, where I met with Elizabeth Pease,
to whom I had written to accompany me in that journey, if she found freedom in her mind.
We had a good meeting with Friends there, and were at Clonmel meeting next day,
which was very large on account of a marriage, and the Lord,
in whom my trust and dependency was, furnished us in an eminent manner,
to the information of those who were strangers,
and the comfort and satisfaction of his own children;
for which I am deeply bowed in thankfulness to him, and made to say,
Let my soul trust in the Lord and serve him forever, for his power is over all,
and therein his poor weak children and servants know victory and dominion;
blessed be his holy name forever and ever.

From thence we went to Cassell, Waterford, Wexford, Lambs-town, Cooladine,
and so to the general Monthly Meeting in the county of Wicklow, which was large.
We had a good opportunity, and were comforted in the enjoyment of the Lord`'s goodness.

Next day we went to Dublin,
where on seventh-day was held the meeting of ministers and elders for that nation,
and next day began the Half-year`'s Meeting.
We had two very large and open meetings that day;
for the great Lord and Master of our assemblies did not
only open a free Gospel-spring in his living ministers,
but also prepared the hearts of the hearers to receive it.
During our stay in that city, we had twelve meetings,
some of which were very glorious and precious seasons,
for which my soul magnifies the Lord, who granted the desire of my heart, which was,
That the power and virtue of Truth might arise into dominion,
so as to reign over that spirit and power which
stood in opposition to the holy Spirit of Christ.
As soon as I lifted up my eyes to behold that city, when I drew nigh to it,
a great weight of exercise laid hold of my mind, and I groaned under it,
both day and night, and fervently breathed to the Lord, in whom I trusted,
that he would be graciously pleased to make way for carrying on his own work,
and give me strength and wisdom to discharge myself faithfully
of the weight I groaned under for the Seed`'s sake,
which I was sensible suffered in that place.
Notwithstanding, the Lord has a true and sincerely concerned people there,
who seek his honour, with whom my soul was truly comforted, and had good unity,
and in that I parted with them in much love and sweetness, being fully clear and easy.
Blessed be the name of our God, who is with his servants and hand-maids,
and makes his children and people, who are baptized into the one spirit,
dear one unto another in the fellowship of the Gospel of peace.

Leaving Dublin we came to John Ashton`'s,
and had a very good meeting amongst a tender newly convinced people,
with whom I was truly comforted, and took my leave of them in abundance of love,
and came to Limerick, had a meeting there, and from thence returned again to Cork.
On first-day following, began the province meeting,
and the next day the men`'s and women`'s meetings.
On third-day, a general public meeting for worship was held,
to which many people came who did not profess with us,
and the Lord was pleased to open many things suitable to their states,
for their information concerning the way of life and salvation;
and his Divine power and presence was with us in a large degree,
to the great comfort and joy of the sincere-hearted,
as well as the tendering of divers who had lived at a distance from,
and in disobedience to, the blessed Truth.
But, oh! the great condescension and love of our compassionate Lord is such,
that he is reaching a hand of help unto all,
and would willingly have the rebellious to turn to him, by unfeigned repentance,
whilst the door of mercy is open.
My soul is deeply bowed before him,
in admiration of his undeclarable love to poor lost mankind,
and a deep travail is in my mind, that the visitations of his love may prevail upon all,
and draw them after himself,
that they may be gathered into the fold of eternal rest and peace.

This meeting being over, I parted with my companion in true love and nearness,
in which we had for some time travelled together.
She returned home, and I finding myself fully clear and easy to leave this nation,
waited at Cork for an opportunity to embark for England; but the wind being contrary,
occasioned my staying there several days,
and I had comfortable seasons amongst my dear friends there.

The wind coming fair, and a ship ready to sail, I took my solemn leave of Friends,
came on board, had a good passage,
and by the protection of Providence got safely to Bristol, where I stayed four days,
and had three good meetings with Friends.
I then took passage in the stage-coach, and came to London in two days,
where I found my dear husband and mother and all well.
We rejoiced to meet once more, and my heart was filled with peace,
and solid satisfaction abounded in my soul, having discharged myself of my duty,
in giving up freely to the service of Truth in this journey.
I am humbly bowed in spirit before the Lord,
whose love and goodness never fail those that trust in him and obey his call,
for he is attending such with his living presence, in their goings out and comings in;
for which my soul, with many more,
is under deep obligation to follow him in all his drawings and leadings forth,
though it be in a cross to our own wills;
and I greatly desire his heavenly will may ever be freely submitted unto,
for he is forever worthy,
and for all his preservation and truth I humbly praise his name.
