[#pike, short="Correspondence with Joseph Pike"]
== Epistolary Correspondence between Deborah Bell and Joseph Pike

[.letter-heading]
Deborah Bell to Joseph Pike.

[.signed-section-context-open]
18th of Twelfth month, 1717.

I think I do daily see more and more need to cry out with thee, O! this inwardness,
this inwardness, is what has been too much wanting in a general way,
and is still wanting.

For it seems to me,
that many are in the high road to ruin for want of this true inward waiting
to know the Spirit of Truth to leaven and subdue their own spirits,
and also to open in them such things as might be
serviceable and beneficial in the churches of Christ,
both with respect to doctrine and discipline.
And I may tell thee,
as one who is not a stranger to the state of the ministry amongst us in this great,
and I had almost said, ungrateful city, that a living ministry is almost lost amongst us;
for here is so much working and studying of the flesh,
and that so well liked and embraced by many,
that the work of the Spirit and motions thereof are very much stopped,
even in such as dwell daily under the baptizings thereof.

It is but a few in comparison,
who have an ear open to hear what the Spirit doth say to the churches;
but when the Spirit doth speak through any, O how do they kick,
and even make a mock at it, and at such as are led and guided by the dictates thereof.
So that things are in a lamentable condition,
and it seems to me the true church is returning into the wilderness again,
where she sits solitary and mournful.
Yet the Lord sees her in her disconsolate state; and my faith is firm,
that the time will come, in which he will bring her back,
and she shall be seen to lean upon the breast of her beloved;
for in him is all her hope and trust.
Many who once were members of her, have forsaken the Lord,
and trusted to and leaned upon the arm of flesh; so that it may be said,
with the prophet in former days, one has builded a wall,
and another has daubed it with untempered mortar.

And I believe the day is coming, in which the wall,
which men have in their own wisdom and strength been building for a shelter to them,
shall fall, and the foundation thereof shall be discovered;
and both the builders and the daubers shall be confounded in that day.
For the Lord will overturn all that is not upon the right foundation,
in the day when he will arise in his power to cleanse his churches and purify his temple.
That we may be of the number, who may be able to stand when he appears,
is what my soul travails for.
It has often been before me of late, that such a day of trial is hastening on,
as will try all to the very bottom, and the strongest will not find anything to boast of;
yet I also believe, the weakest babes in Christ who keep their habitation,
shall be strengthened to go through whatsoever may be
suffered to come upon them for the trial of their faith,
that so it may be more precious than that of gold.
I do not see any need the faithful have to be discouraged:
for though there be a suffering with Christ for a time,
yet there will be a reigning with him also.
And though the followers of the Lamb may seem but a few,
and his enemies a great multitude,
yet the Lamb and his followers will obtain the victory at last, and triumph over all.

Whilst I am thus going on, I am ready to check myself,
why I should write after this manner to one who knows more than I do,
and whose experience far excels mine,
from whom I had more need to receive both counsel and encouragement; for I am often,
in the sight of things and the sense of my own weakness, made to cry out,
who shall continue to the end in well-doing, so many are the wiles of Satan to weaken,
and if possible, destroy the faith of God`'s poor children.
Surely we have need of one another`'s prayers; and as the Lord opens, strengthens,
and enlarges my heart towards himself, I am not unmindful of my near and dear friends.
I desire to be remembered also by thee,
and to be frequently visited by thy fatherly epistles, as freedom and opportunity admit;
and keep nothing back that may be in thy mind towards me,
for I have an open heart to receive good counsel.

[.signed-section-signature]
Deborah Bell.

[.letter-heading]
Deborah Bell to Joseph Pike.

[.signed-section-context-open]
12th of Fourth month, 1718.

The church is in my judgment in a poor condition,
and many of her living members are almost overborne and
crushed by those who are in such a state as renders them
incapable of membership in that body which has a holy Head,
and is made all holy by the virtue and power which
flows from Him and circulates through every member.
But such is the declension of this age,
that I fear too many who are accounting themselves members of this holy body,
know very little what holiness is, at least as to the practice of it.

It is as if some now-a-days did not believe that text,
"`Without holiness none shall see the Lord,`" except they think
holiness consists in talking of good things now and then.
Indeed, talking is the highest attainment some are come to,
and by their fair speeches and feigned words they deceive the simple,
but cannot deceive such as have a true discerning,
and are minding more how they walk than how they talk.
For it is come to that pass now, that people must not trust one another by bare talking,
though it be with seeming sanctity;
but we have need to wait for wisdom from Him who is an all-seeing, all-knowing God, lest,
like Samuel, we think the Lord`'s anointed is before us, when indeed it is not so,
but rather such as are despising those whom he has chosen,
and are exalting self above the cross of Christ.
Such we have amongst us, who would sway in the church, and they do a deal of harm.
My spirit is exercised before the Lord in a fervent cry to him,
that he will fill his faithful people more and more with the spirit of discerning,
that so all such deceivers may be seen, and a hand stretched forth against them;
that the mischief which otherwise they would do may be prevented;
and this will help mightily to reform the people.
For I am fully of the mind,
that the greatest hurt and obstruction of God`'s
glorious work lies amongst some called ministers,
and such as are next in degree to them.

[.signed-section-signature]
Deborah Bell.

[.letter-heading]
Deborah Bell to Joseph Pike.

[.signed-section-context-open]
London, 9th of Ninth month, 1718.

Some of thy good fatherly counsel and experience would
be very acceptable and I believe profitable to me,
who am one that often wades as in very deep places,
and am in great sorrow and affliction for Zion`'s sake.

According to my sense and judgment, she is in a very mournful state,
and is rather going into than returning out of the wilderness.
And that which most deeply affects my heart, is,
that too many who pretend to be watchmen upon her walls
are exceedingly ignorant of her condition,
and instead of giving a faithful warning of approaching danger,
and seeking to make up the breach and stand in the gap,
are with might and main seeking to make the breach wider.
By this means a door is opened to let in a flood of wickedness,
which if the Lord God of Zion do not, by a mighty hand, put a stop to,
I am afraid will prove a flood of utter ruin to abundance +++[+++of persons.]
For surely we have cause to say, the day is come,
in which abominations are found amongst such as are
accounting themselves the messengers of our God,
and are pretending to act from the motion of his Holy Spirit; +++[+++who are]
stamping things higher than is requisite, even if it came from such as are,
what these only pretend to be.
When I hear such things, and also hear and see how loose, frothy,
and vain such are when in company, it greatly wounds my very soul, and I am ready to say.
Truth will never prosper in a general way as formerly +++[+++it did,]
whilst such as make so high a profession of it,
live and walk from under the power of the cross of our Lord Jesus Christ.

This cross is very little borne now-a-days, except by a small remnant,
and these are by the others accounted a narrow-spirited people,
who say they make the way more narrow than there is need for.
But sometimes I am ready to fear, such have either never entered in at the strait gate,
or else after some time have returned back into the broad way again.
Such may well be numbered among some of old, whom the apostle calls foolish,
because they did not obey the Truth after it was revealed,
but having begun in the Spirit, sought to be made perfect by the flesh.
This seems to be the state of many in our day;
and what will be the consequence of these things is known unto Him that knows all.
For my part I do fully expect, that except timely repentance be known,
of which I see little hopes at present,
the Lord will bring a sore and grievous judgment
upon the professors of his Truth and name,
which will fully manifest the hypocrite and double-tongued.
And though the apprehension of this terrible day may be
ready to strike a terror into the minds of the upright,
and make them say.
Who shall be able to stand in that day, and abide the trials thereof? Yet methinks,
as in the administration of condemnation and judgment spiritually,
there is a beauty and glory beheld by all such souls as
are willing to abide the days of their purification;
so likewise, in the administration of judgment outwardly,
in order to separate the pure from the impure and the chaff from the wheat,
there will be a beauty and glory beheld.
And though the gold must pass through the fire as well as the dross,
yet the effect will be different, for it will destroy the one,
and make the other more pure and beautiful;
and though the winds blow hard upon the wheat, yet it will not be driven away,
but only the chaff, which is not fit to be gathered into the garner of God`'s power.
And in those days, precious unto the Lord will such be,
as in sincerity and true-heartedness have loved, served, and feared him above all.
The daily cry of my poor soul unto my God is, that I may be one of that number,
whatsoever exercises it may be my lot to go through for
the Seed`'s sake in this suffering day.
And as it is my cry to the Lord for myself, so even for many more,
and I do find it my duty to pray for my near and dear friends everywhere,
and I also earnestly desire to have the benefit of their prayers for me,
and in particular thine, my dear friend,
as knowing thee to be one who often goes deep in
spirit before the Lord on account of his people.
I also desire a full and free account in writing of thy present
apprehensions touching the state of the church in general,
that I may know whether we be like-minded.
I think we ever were when together,
and as we still abide near that Fountain of love and life,
by which we were made to love one another, which love is stronger than death,
we shall still abide in the oneness, and see by the eye of faith the same things,
and so be a help, strength, and confirmation one to another.

[.signed-section-signature]
Deborah Bell.

[.letter-heading]
Deborah Bell to Joseph Pike.

[.signed-section-context-open]
24th of Second month, 1719.

[.salutation]
My good and worthy friend.

Thy kind and acceptable letter of the eighth month, I received,
and was very glad to hear from thee; for I thought it long before I had thine,
and many fears did attend my mind concerning thee, lest thou hadst been worse than usual,
which thoughts are very afflicting to me;
for I am desirous if it be the Lord`'s will that thy days may be prolonged in this world,
for divers reasons which are often under my
consideration when I hear of thy indisposition.

The Lord in his tender mercy look down upon his church in
general and the families of this people in particular,
and administer suitably to the present condition
and circumstances of his people everywhere,
is my cry to him,
and preserve for ever under the shadow of his
heavenly wing and in the pavilion of his power,
such as are bent for his glory and the good of his people above all.
For many are the poisoned arrows which the enemy is shooting at such,
because they stand as in the front,
and are boldly fighting with the sword of the Spirit
against the wicked one in all his appearances.

These true-hearted soldiers often meet with very close engagements,
by reason of so many who pretend to be of the disciples and followers of Christ,
deserting their master and starting aside out of their places;
and this makes not only the battle the harder upon such as dare not quit their posts,
but it also makes the breach the wider which ought to be made up.
How these expect to escape that woe,
which is pronounced upon such as will not stand in the
gap and make up the breach for the house of Israel,
I know not.
But it is to be hoped,
the Lord in his own time will arise for his own name and suffering Seed`'s sake,
which even groans and cries from a sense and sight of the abomination, which will,
if not speedily purged out, bring desolation.
And indeed desolation is already come upon many, who once knew a good condition,
and the greatest misery of such is, they are not sensible of their poor, empty,
desolate state, but, too much like some of old, are thinking themselves rich and full,
wanting nothing.
And such as these are very apt to set themselves on high,
and are speaking peace to their poor souls, saying, We shall see no sorrow;
when alas! the Holy Spirit is telling them plainly,
both immediately in themselves and through the faithful,
that they are deceived by the great deceiver of souls, for their state is quite contrary,
namely, poor, naked, blind and miserable, and wanting all things.
But O, how hardly doth this plain dealing go down with this wise, conceited,
self-righteous people; for with sorrow I write it,
there are very few in these days who have an ear
to hear what the Spirit saith unto the churches,
and indeed the voice and language of the Spirit is very
little to be heard in the church now-a-days.
For though at times the Lord is laying a constraint upon his true ministers,
such as mourn between the porch and the altar,
and they are made to open their mouths in his dread, being filled with his eternal word,
and they at times warn both professors and profane of
the day of vengeance which is even at hand;
yet when such have warned people, they, much like the old prophets,
are even as it were separate from all, and dwell in solitary places,
till sent again with a fresh message.
But in the main, the spring of the ministry is very much stopped,
and true ministers shut up, especially towards the professors of Truth;
yet we have abundance of preaching amongst us, but +++[+++chiefly]
from the letter which killeth.

This was much in my heart, as I sat in our meeting at the Bull and Mouth this day:
when things will be better I know not:
the Lord help and deliver his poor mourners for his own great name sake,
is the cry of my exercised soul.

Now, dear Joseph, I cannot well forbear giving thee hints concerning things of this kind;
for my heart is often very full in the consideration of the state of many,
and I take the liberty to open myself to thee,
well knowing thee to be one who travails for Zion`'s prosperity,
and can deeply sympathize with her mourning children,
who are often in deep sorrow for her sake, and are crying.
How long, O Lord! will it be,
ere thou take unto thyself thy great power and reign over all in thine excellent glory.
But although it is very unpleasant to see Truth trampled upon and under suffering,
and its faithful servants suffering with it; yet I do believe,
the greater its suffering is,
and the lower we bow and are baptized in a pure
sympathy with the blessed suffering Spirit,
the higher we shall be raised by the Truth, when it arises.
For it must arise and come into dominion over all opposers and gainsayers;
and blessed will all such be who are willing to keep company with it,
and not only to believe in, but even to suffer with it and for it.
I have sometimes thought,
it is not a hard thing to follow Truth when it is
exalted and triumphs over all and reigns in glory,
then many will speak well of it; but when it comes to suffer, be buffeted,
mocked and reviled, then comes the trial of our love,
and many we see who are not willing or able to bear these things.

[.signed-section-signature]
Deborah Bell.

[.letter-heading]
Joseph Pike to Deborah Bell.

[.signed-section-context-open]
Cork, 3rd of Ninth month, 1720.

[.salutation]
Dear friend, Deborah Bell,

Thy long looked for letter of the 1st of seventh month past,
by our friend Jonathan Hutchinson, came lately to my hands, and though long expected,
yet was very acceptable.

The contents is matter of affliction, in that thou had no better account to give,
relating to the affairs of the church in general,
as well as the dishonour brought upon the holy Truth,
by the ill conduct or management of some in high stations therein,
which I find has affected thee to that degree,
as to have influence on thy state of health.
I can in truth say, it hath also affected me under the consideration of these things.
What will be the end thereof, while the leaders of the people,
by giving hurtful or evil examples, do cause spiritual Israel to go astray and err,
as they did of old; and who,
instead of standing in the gap and making up the
breach against an overruling spirit of pride,
and eagerly, nay violently, pursuing and running into and after the world,
do themselves lead the way, and example the people into it,
and thereby bring dishonour and reproach upon the Lord`'s blessed Truth,
as well as lay a stumbling block in the way of the weak and well inclined.

Surely the Lord is greatly displeased with such leaders,
and I do greatly fear his heavy hand of judgment will be stretched out against them,
as it hath already in a measure appeared by the late terrible stroke
given to that unbounded grasping and coveting after the world.
With what face, if they dare appear,
can such preachers pretend or preach that we are a self-denying people,
redeemed from the world, and that we follow Christ by taking up the daily cross,
when at the same time their actions and conversation give the lie to their tongues.
Such preachers and pretenders as these,
must and will most assuredly receive a double reward
due to unfaithful and negligent servants or stewards,
unless they greatly repent.
And yet, notwithstanding all this.
Truth is Truth still, and will stand over the heads of such, and remain for ever.

The prospect and consideration of things as they are at present,
is matter of great mourning and lamentation to the upright in heart,
who keep their habitation in the Lord`'s everlasting Truth,
and who are not yet without hope,
that the Lord will arise and plead his own cause for his name and glory`'s sake.
Amen.

[.signed-section-signature]
Joseph Pike.
