== A Supplement, by Her Husband.

Besides the foregoing account of her labours and travels,
she went several other journeys, wherein I was mostly her companion,
but she omitted keeping a particular account.

During our residence at Bradford, she accompanied me twice into Cumberland,
and also into several parts of Westmoreland and Lancashire,
where her service was very acceptable to the churches.
After our removal to London, she was divers times at Bristol,
Bath and some other meetings thereabouts; once at their Quarterly Meeting at Bristol,
where she had good opportunities, and was of great service,
as divers of them afterwards told me.
She had many invitations to pay them another visit, and spend some time with them,
alledging, she might be of great service to their youth, with whom she had great place;
but she was steady,
and ever careful not to be drawn by any thing but the openings of Truth.
Her concern was, to be led into all her services by the spirit of Christ,
which only can enable ministers, and make them serviceable in his church;
often observing to me in our private conversation,
what a weighty thing it was to travel to publish the Gospel,
and preach the doctrines of the kingdom of God;
and that all ministers had need to be very steady,
and often retire and wait diligently upon the Lord,
to see their way clearly opened in the light of Truth,
and to be led into all their services by the holy Spirit, that certain guide,
by which none were ever led astray; and she had observed,
for want of this care and steadiness, other motives had prevailed with some,
and they had suffered loss.

In the year 1730,
we took our journey in order to visit some meetings in the north of England,
and travelled by Royston and Huntington to York, and had two meetings in that city,
where she had good service.
From thence to Leeds, Bradford, and Carlisle, and visited meetings in that county.
Then returning by Wigton, Pardsay, and Cockermouth,
we had comfortable meetings amongst our dear friends and former acquaintances.

Leaving Cumberland, we came to Kendal, and were at their meetings on first-day,
where she had good opportunities.
From thence to Settle Monthly Meeting, and next day to Skipton meeting; then to Bradford,
where we had a large meeting, many people coming in of her former acquaintance,
and the power of Truth was with us, and in the authority thereof,
she preached the Gospel of life and salvation.
Many were affected, and much reached and tendered, for her heart was opened,
and she was largely drawn forth, and enabled by the Truth to lay open to them,
and zealously to recommend and press home, the doctrines of Christ our Saviour,
in the power and demonstration of his own Spirit,
to the great satisfaction and comfort of Friends.

We came from thence to Leeds, had a good opportunity with Friends,
and proceeded to Nottingham, where we staid the first-day meetings.
In the afternoon the meeting was very large, and she had an excellent opportunity,
being enabled through Divine assistance,
to preach the Gospel of glad-tidings and salvation, through faith in Christ,
freely to them.
All were quiet and attentive to Truth`'s testimony; the power of the Lord came over all,
and it was a comfortable season.
From thence in three days we came safe to London, with peace and satisfaction.

In the year 1736, after our Yearly Meeting at London, we went to Banbury Yearly Meeting,
and had a meeting at Hitchin in our way.
She had divers good opportunities at that Yearly Meeting, which was large.
We set forward next morning towards Northampton,
and had a meeting at Bugbrook that evening, where many professors came,
and she was enabled to preach the Gospel to them,
and declare the way of life and salvation,
as it was made freely manifest by the light of Christ shining in the heart.
It was a good opportunity, and Truth`'s testimony had an affecting reach upon many.

Next morning we came to Northampton Quarterly Meeting, where many Friends met,
and she had divers excellent opportunities there,
particularly at the meeting of ministers,
greatly to the comfort and satisfaction of the few ministers in that county,
and others met with them.
Being fully clear, we set forward for London, and came safe home in peace.

Having drawings in her mind to visit her native country once more,
the latter end of this summer we set forward in
company with our friend and cousin Thomas Story.
We had meetings at Albans, Sherrington, Wellingborough, Leicester, Nottingham,
and Sheffield, where she had good opportunities, and discharged herself faithfully.
Thence we came to Leeds, and were at that meeting.
Thomas Story leaving us there, travelled northward, but we staid some time longer,
and then went to Bradford, and were at that meeting on a first-day.
A large assembly of Friends and others came together,
having notice of our intention of being there,
and her heart was wonderfully opened amongst them;
many Gospel truths were set in a clear light,
and declared in the power and demonstration of the Spirit of Christ;
an open door appeared to receive the testimony,
and many were affected and reached by the Truth.

We staid thereabouts some time,
and she visited many of her friends and former acquaintance;
and also attended the meetings at Rawden, Gildersome, and Brighouse,
where she had good service.
From thence we went to Manchester, being accompanied by our dear friend Tabitha Hornor,
where we had divers meetings to good satisfaction.
My wife desiring to see that worthy Friend and servant of Christ, Benjamin Bangs,
(for she ever dearly loved those who had faithfully
served the Lord in the prime of their time,
and retained their integrity in old age,) we went to Stockport, in Cheshire,
and he received us with open arms, like a father in Christ.
We had a meeting where he was present, and she had good service,
and we were much comforted in his company.

From thence we returned by Manchester and Halifax, and afterwards went to Leeds.
We spent some time with our friends there, to their satisfaction and our comfort,
and were several times at their meeting, where she had good service.
We also went to their Monthly Meeting held at Bradford, where she had an excellent time;
and afterwards to the Quarterly Meeting at York, where she had good opportunities.

When that meeting was over, she took her solemn leave of her friends in that country,
in much tenderness, for the Lord had wonderfully owned us together with his goodness,
in that her last visit to them,
which greatly strengthened the bands of that true love and nearness,
which had subsisted from her minority.
It proved a parting time indeed, and her last farewell to most of them.
We then set forwards towards home; came to Mansfield on first-day morning,
staid both meetings, and to Nottingham that night; next day to Leicester,
and so got safely to London the fore part of the eighth month,
through some hardship and difficulty, the weather being very wet and turbulent.
We came home in perfect peace, with thankful hearts before the Lord,
for his preservation and good presence,
that had attended and made our journey truly comfortable and satisfactory to us;
for which he shall have the praise, who is for ever worthy.

In the year 1737, she inclining to be at the Yearly Meeting at Tenbury,
in Worcestershire, to be held for the western counties,
we set forward in company with our worthy friend Joseph Ollive,
and were at the meeting at High-wickham; after which we proceeded to Worcester,
and went in company with many Friends from thence to Tenbury.
We had several large meetings in that place,
wherein she had divers opportunities and good service.
We thence returned to Worcester, and had a meeting with Friends there;
from thence to Eversham, and visited that meeting; and so to Warwick,
and were at their meetings on first-day, which were large;
wherein she had good opportunities to declare the truth.
Next day we had a meeting at Coventry, which was large,
and the power of Truth was with us, and she had good service for the Lord in that place.
Then being clear and easy, we came directly home,
with thankfulness in our minds to the Almighty, for his mercy and goodness,
who is always near to his depending servants, that are truly devoted in heart to him,
and through Divine assistance are answering his requirings.

Having had for some time drawings in her mind to visit Friends at Royston,
and Huntington, in the seventh month we undertook that journey,
though she was then very weakly; for through hard travail and close exercise,
and her often infirmities, her natural strength was much decayed,
yet not very perceptible in her public service.
In our way we had meetings at Ware and Hertford; then coming to Huntington,
we were at that meeting on a first-day, which was pretty large,
divers Friends coming from parts adjacent.
She had a good opportunity to discharge herself of the concern that was upon her,
and we had a satisfactory and comfortable time.
In the evening we had a meeting at Godmanchester in the school-house,
where many people came, and she was enabled to preach the Gospel of life and salvation,
in the power and authority of the Spirit of Christ,
to the comfort and satisfaction of many.

In our return from thence, we had a meeting at Royston,
where we were comforted in the enjoyment of the love of God amongst Friends.
In our way home we staid Tottenham meeting, and then came to our outward habitation,
she being perfectly clear and easy, having faithfully performed this her last journey;
and how it fared with her afterwards,
I refer to the testimony I have written concerning her.
